# -*- coding: utf-8 -*-
r"""r2a_common.py -- C2 rev 2 REVISER A (2026-10-01): ONE source of truth for every design and implementation this
reviser evaluates, and the shared plumbing (paths, members, tables).  ANALYSIS ONLY: builds no image, flashes nothing,
sends nothing, writes nothing outside analysis-2020accord/studies/angle_loop/c2/rev2A/ and _scratch/angle_loop/c2rev2A/.

DESIGNS (each a loop STRUCTURE) and IMPLEMENTATIONS (each a concrete byte/cal set of that structure):

  design P  "fresh-rate D"   C1r2 skeleton (P + I on the held angle error, G(v) speed walk, I freeze) with the D operand
                             = the FRESH 1 kHz motor-rate EMA gp-0x6abe, zeroed by Honda's own validity form, handed to
                             Honda's D multiply in r26 (0x29EE0 mov r26,r8 ; nop).  The panel's D2a structure.
      P1  D2a as the panel fitted it          Kd 34, 7-knot table (panel DS_ROWS['D2a'])
      P2  6-knot table                        Kd 34, refit under D2a's own envelope without the 15.5 m/s knot (-6 B)
      P3  Kd 41                               refit 7-knot table under its own envelope
      P4  Kd 48                               refit 7-knot table under its own envelope (M20 nearest V295's)
  design F  "held-rate D"    the same skeleton with C1's E5: D on the 100 Hz-held gp-0x6a56 (the flown V295/C1 D class).
      F1  B0r as the panel fitted it          Kd 20, 7-knot table (panel DS_ROWS['B0r'])
      F2  6-knot table                        Kd 20, refit under B0r's own envelope without the 15.5 m/s knot (-6 B)
  design Z  "zero cave"      A1 + B2 (Honda's Kp/Kd LERPs re-keyed to speed>>8, flat Ki, no I freeze): the bytes floor,
                             scored as the reference that FAILS the goal (turn-hold at highway), never as a contender.
  the rest of the panel      A2, B1, B2+guard, B3, CGF-1+guard, D1a..D3b -- scored by the common time scorer only.

Every number this reviser reports is regenerated by a script in this folder from these definitions."""
from __future__ import annotations

import json
import os
import sys
from dataclasses import replace
from pathlib import Path

import numpy as np

os.environ.setdefault("OPENBLAS_NUM_THREADS", "1")
os.environ.setdefault("OMP_NUM_THREADS", "1")
os.environ.setdefault("ACCORD_FIRMWARE_ROOT", "C:/Users/dudei/Desktop/Projects/accord-firmwares")

HERE = Path(__file__).resolve().parent                      # .../studies/angle_loop/c2/rev2A
AL = HERE.parents[1]                                         # .../studies/angle_loop
KIT = AL.parents[2]                                          # repo root
for _p in (str(AL / "panel"), str(AL / "panel" / "D-structure"), str(AL / "c1"), str(AL / "refute_stability"),
           str(AL.parent / "v295" / "plant"), str(AL)):
    if _p not in sys.path:
        sys.path.insert(0, _p)

OUT = KIT / "_scratch" / "angle_loop" / "c2rev2A"
OUT.mkdir(parents=True, exist_ok=True)
DS_OUT = KIT / "_scratch" / "angle_loop" / "D-structure"

import ds_model as DM  # noqa: E402
import c1_lib as C  # noqa: E402

V295_SHA = "5c044d6576314052"

# ---------------------------------------------------------------------------------------------------------------------
# knot speeds
# ---------------------------------------------------------------------------------------------------------------------
KNOTS7 = [3.1, 8.0, 10.0, 11.75, 15.5, 17.5, 26.9]           # the C1 lib knot speeds (= the panel D-structure fits)
KNOTS6 = [3.1, 8.0, 10.0, 11.75, 17.5, 26.9]                 # drop 15.5 (nearly collinear in both panel tables)
KNOTS5 = [3.1, 8.0, 10.0, 11.75, 26.9]                       # drop 15.5 and 17.5 (the size floor of this walk)

# panel tables, verbatim (score_freq.DS_ROWS); asserted equal to the D designer's final_tables.json on import of r2a_tables
PANEL_ROWS = {
    "B0r": [(714, 1187, 896), (1843, 1434, -6388), (2304, 715, -1779), (2707, 540, 2489), (3571, 1065, 2781),
            (4032, 1378, 1297), (6198, 2064, 0), (0xFFFF, 2064, 0)],
    "D2a": [(714, 1195, 1204), (1843, 1527, -7988), (2304, 628, -925), (2707, 537, 2773), (3571, 1122, 2941),
            (4032, 1453, 1278), (6198, 2129, 0), (0xFFFF, 2129, 0)],
}

# ---------------------------------------------------------------------------------------------------------------------
# the implementations of designs P and F (the contenders).  struct = the ds_model.Des for the loop STRUCTURE (G is set
# per speed from the table); table = 'panel:<id>' or 'fit:<env-id>:<knots>'; listing = the ds_asm listing id
# ---------------------------------------------------------------------------------------------------------------------
STRUCT = {
    "fresh34": DM.Des("fresh-rate D, Kd 34", dsrc="op", dop="fresh_rate", kd=34),
    "fresh41": DM.Des("fresh-rate D, Kd 41", dsrc="op", dop="fresh_rate", kd=41),
    "fresh48": DM.Des("fresh-rate D, Kd 48", dsrc="op", dop="fresh_rate", kd=48),
    "held20": DM.Des("held-rate D (C1 E5), Kd 20", dsrc="rate_held", kd=20),
}
# envelope source per structure: the D designer's cached envelope where it exists (same structure, same member set,
# same grid -- r2a_env.py re-derives one of them as a reproducibility control), else this reviser's own run
ENV_SRC = {"fresh34": ("DS", "D2a"), "held20": ("DS", "B0r"), "fresh41": ("R2A", "fresh41"), "fresh48": ("R2A", "fresh48")}

IMPLS = {
    "P1": dict(design="P", struct="fresh34", table="panel:D2a", listing="D2a",
               note="D2a exactly as the panel fitted it (Kd 34, 7 knots)"),
    "P2": dict(design="P", struct="fresh34", table="fit:fresh34:6", listing="D2a",
               note="Kd 34, 6-knot refit under D2a's envelope (no 15.5 m/s knot): -6 B"),
    "P5": dict(design="P", struct="fresh34", table="fit:fresh34:5", listing="D2a",
               note="Kd 34, 5-knot refit under D2a's envelope (no 15.5 / 17.5 m/s knots): -12 B"),
    "F1": dict(design="F", struct="held20", table="panel:B0r", listing="B0",
               note="B0r exactly as the panel fitted it (held-rate D Kd 20, 7 knots)"),
    "F2": dict(design="F", struct="held20", table="fit:held20:6", listing="B0",
               note="held-rate D Kd 20, 6-knot refit under B0r's envelope (no 15.5 m/s knot): -6 B"),
}


# evaluated and REJECTED at the envelope stage (r2a_env.py / r2a_fit.py): raising the fresh-rate Kd above 34 makes the
# D term's OWN loop cross unity against the lowest credible damping (D_T = (Kd/8) * 4.712 * 0.160 T per deg/s: 3.20 at
# Kd 34, 3.86 at 41, 4.52 at 48, vs b_lo / the b_q floor 3.46 T per deg/s), so the envelope collapses to 0 at
# 12.5-15 m/s (Kd 41: b_q*J_hi / b_q*J1.0) and at 1-10 m/s (Kd 48: b_lo) -- see r2a_fit_out.txt
REJECTED = {
    "P3": dict(design="P", struct="fresh41", table="fit:fresh41:7", listing="D2a",
               note="Kd 41 (cal-only vs P1), 7-knot refit under its own envelope"),
    "P4": dict(design="P", struct="fresh48", table="fit:fresh48:7", listing="D2a",
               note="Kd 48 (cal-only vs P1), 7-knot refit under its own envelope"),
}


def env_of(struct):
    src, key = ENV_SRC[struct]
    if src == "DS":
        d = json.loads((DS_OUT / "final_env.json").read_text())[key]
    else:
        d = json.loads((OUT / f"env_{key}.json").read_text())
    return {float(v): g for v, g in d["env"].items()}, {float(v): b for v, b in d["bind"].items()}


def tables():
    """{impl id: table rows} -- panel rows verbatim, fitted rows from r2a_tables.json (r2a_fit.py)."""
    fitted = json.loads((OUT / "r2a_tables.json").read_text()) if (OUT / "r2a_tables.json").exists() else {}
    out = {}
    for k, im in IMPLS.items():
        if im["table"].startswith("panel:"):
            out[k] = [tuple(r) for r in PANEL_ROWS[im["table"].split(":")[1]]]
        elif k in fitted:
            out[k] = [tuple(r) for r in fitted[k]]
    return out


def des_of(impl_id):
    return STRUCT[IMPLS[impl_id]["struct"]]


def G_at(v, tbl):
    return C.cave_G(C.spd_counts(v), tbl)


def cand_freq(impl_id, tbl):
    """the score_freq.Cand for an implementation (the common frequency scorer's own candidate type)."""
    import score_freq as SF
    d = des_of(impl_id)
    if d.dsrc == "op":
        return SF.Cand(impl_id, "rev2A", kind="angle", dsrc="op", dop="fresh_rate",
                       cont=SF.cave_cont_rows(tbl, 112, 56, int(d.kd)), note=IMPLS[impl_id]["note"])
    return SF.Cand(impl_id, "rev2A", kind="angle", dsrc="rate_held",
                   cont=SF.cave_cont_rows(tbl, 112, 56, int(d.kd)), note=IMPLS[impl_id]["note"])


def lane_cfg(impl_id, tbl):
    """the DSLane column config (integer-exact lane) for an implementation."""
    import ds_selftest as ST
    return ST.lane_cfg(des_of(impl_id), tbl)


def table_bytes(tbl):
    return b"".join(int(X).to_bytes(2, "little") + int(G).to_bytes(2, "little") + (int(S) & 0xFFFF).to_bytes(2, "little")
                    for (X, G, S) in tbl)
