# -*- coding: utf-8 -*-
r"""r2a_time_report.py -- the tables of the COMMON TIME SCORER (score_time.py) and the pre-registered bars, generated
from its result caches (_scratch/angle_loop/c2rev2A/time_full.json, time_dense.json).  Nothing here is typed by hand.
ANALYSIS ONLY.   usage: python r2a_time_report.py      (writes score_time_out.md)"""
from __future__ import annotations

import json

import numpy as np

import r2a_common as R

BANDS = (("3-5", 0.0, 7.0), ("8-12.5", 7.5, 13.0), ("15-19", 14.0, 20.0), ("22-30", 21.0, 31.0))
HF_LINE = 2.0


def load(tag):
    d = json.loads((R.OUT / f"time_{tag}.json").read_text())
    T = {}
    for r in d["results"]:
        T[(r["name"], float(r["v"]), r["member"])] = {k: np.array(v, float) for k, v in r["metrics"].items()}
    return d["labels"], T


def agg(T, name, metric, mem, lo, hi, j, fn=max):
    vals = [T[(n, v, m)][metric][j] for (n, v, m) in T if n == name and m == mem and lo <= v <= hi
            and metric in T[(n, v, m)]]
    return fn(vals) if vals else float("nan")


def main():
    labs, T = load("full")
    mems = sorted({m for (_, _, m) in T}, key=lambda m: ("nominal", "bc", "F_hi", "b_lo*J_hi", "nominal+h10").index(m))
    L = []
    P = L.append
    P("# COMMON TIME SCORER -- results (generated by r2a_time_report.py from score_time.py's caches)")
    P("")
    P("Every column below ran in the SAME batch per (scenario, speed, member): identical plant, sensors, noise seed and "
      "fork frames.  Speeds 3.1 5 8 10 11.9 12.5 15 17 19 22 26.9 30 m/s.  P1 == the panel's D2a and F1 == the panel's "
      "B0r byte for byte (score_time_selftest.txt CONTROL 3).")
    P("")
    for mem in mems:
        P(f"## member `{mem}`")
        P("")
        P("| column | dj ev 3-5 | dj ev 8-12.5 | dj ev 15-30 | stick % 3.1 | hold slips 15-30 | turn-hold min >=8 | s02 gain >=8 | "
          "s05 gain >=8 | step ovs % | lurch firm deg | lurch light400 | light1000 | latch ovs | engage droop | "
          "sentinel push | tmo hold dev | tmo T after | co-steer droop | dead band deg | hard16/ref max | T 5-30 holds | "
          "T 40-200 | det frac/rev | wraps |")
        P("|" + "---|" * 25)
        for j, lab in enumerate(labs):
            def dj(lo, hi):
                s = 0.0
                for nm in ("s02", "s05", "ssm"):
                    s += sum(T[(n, v, m)]["dj_events"][j] for (n, v, m) in T if n == nm and m == mem and lo <= v <= hi)
                return s
            st31 = max(T[(n, v, m)]["stick_pct"][j] for (n, v, m) in T if n in ("s02", "s05", "ssm") and m == mem
                       and abs(v - 3.1) < 0.01)
            slips = sum(T[(n, v, m)]["hold_slips"][j] for (n, v, m) in T if n == "rh" and m == mem and v >= 14)
            hold = agg(T, "rh", "hold_ratio", mem, 7.9, 31, j, min)
            g02 = (agg(T, "s02", "track_gain", mem, 7.9, 31, j, min), agg(T, "s02", "track_gain", mem, 7.9, 31, j, max))
            g05 = (agg(T, "s05", "track_gain", mem, 7.9, 31, j, min), agg(T, "s05", "track_gain", mem, 7.9, 31, j, max))
            stov = agg(T, "st", "overshoot_pct", mem, 0, 31, j)
            lf = agg(T, "ov_fade", "lurch_overshoot", mem, 0, 31, j)
            l4 = agg(T, "ov_light400", "lurch_overshoot", mem, 0, 31, j)
            l10 = agg(T, "ov_light1000", "lurch_overshoot", mem, 0, 31, j)
            lat = agg(T, "ov_latch", "lurch_overshoot", mem, 0, 31, j)
            dr = agg(T, "eng_load", "droop", mem, 0, 31, j)
            sen = max(agg(T, "sen_L16", "sen_excursion", mem, 0, 31, j), agg(T, "sen_R16", "sen_excursion", mem, 0, 31, j))
            tmd = agg(T, "tmo", "tmo_hold_dev", mem, 0, 31, j)
            tma = agg(T, "tmo", "tmo_T_after", mem, 0, 31, j)
            csd = agg(T, "cs", "cs_droop", mem, 0, 31, j)
            dbl = agg(T, "db", "db_lag", mem, 0, 31, j)
            hr = max((T[(n, v, m)]["hard16"][j] / max(T[(n, v, m)]["hard16_ref"][j], 1e-9)) for (n, v, m) in T
                     if n == "hard" and m == mem)
            thf = max(agg(T, "rh", "T_hf", mem, 0, 31, j), agg(T, "st", "T_hf", mem, 0, 31, j))
            t100 = agg(T, "s05", "T_100", mem, 0, 31, j)
            det = max(T[k]["det_max_frac"][j] for k in T if k[2] == mem and "det_max_frac" in T[k])
            drv = max(T[k]["det_count"][j] for k in T if k[2] == mem and "det_count" in T[k])
            wr = max(T[k]["wraps"][j] for k in T if k[2] == mem and "wraps" in T[k])
            P(f"| {lab} | {dj(0, 7):.0f} | {dj(7.5, 13):.0f} | {dj(14, 31):.0f} | {st31:.1f} | {slips:.0f} | {hold:.3f} | "
              f"{g02[0]:.2f}-{g02[1]:.2f} | {g05[0]:.2f}-{g05[1]:.2f} | {stov:.1f} | {lf:.2f} | {l4:.2f} | {l10:.2f} | "
              f"{lat:.2f} | {dr:.2f} | {sen:.2f} | {tmd:.2f} | {tma:.0f} | {csd:.2f} | {dbl:.2f} | {hr:.2f} | {thf:.2f} | "
              f"{t100:.2f} | {det:.3f}/{drv:.0f} | {wr:.0f} |")
        P("")
    # ---- the pre-registered bars, per column, over every member and speed
    P("## The pre-registered bars (score_time.py docstring), every member, every speed")
    P("")
    P("| column | hold >= 0.90 at >= 8 m/s | line: T 5-30 holds <= 2.0 & 0 detector reversals | sentinel push <= 0.1 deg | "
      "tmo: |T| < 50 by sentinel + 0.25 s | 0 int32 wraps | verdict |")
    P("|---|---|---|---|---|---|---|")
    verdict = {}
    for j, lab in enumerate(labs):
        hold = min(T[k]["hold_ratio"][j] for k in T if k[0] == "rh" and k[1] >= 7.9)
        thf = max(max(T[k]["T_hf"][j] for k in T if k[0] in ("rh", "st")), 0)
        drv = max(T[k]["det_count"][j] for k in T if "det_count" in T[k])
        sen = max(T[k]["sen_excursion"][j] for k in T if k[0].startswith("sen"))
        tma = max(T[k]["tmo_T_after"][j] for k in T if k[0] == "tmo")
        wr = max(T[k]["wraps"][j] for k in T if "wraps" in T[k])
        ok = [hold >= 0.90, thf <= HF_LINE and drv == 0, sen <= 0.1, tma < 50, wr == 0]
        verdict[lab] = all(ok)
        P(f"| {lab} | {hold:.3f} {'PASS' if ok[0] else 'FAIL'} | {thf:.2f} / {drv:.0f} {'PASS' if ok[1] else 'FAIL'} | "
          f"{sen:.2f} {'PASS' if ok[2] else 'FAIL'} | {tma:.0f} {'PASS' if ok[3] else 'FAIL'} | {wr:.0f} "
          f"{'PASS' if ok[4] else 'FAIL'} | {'PASS' if all(ok) else 'FAIL'} |")
    P("")
    # ---- dense
    D = None
    for tg in ("dense", "dense2"):
        try:
            labs_d, Dx = load(tg)
        except FileNotFoundError:
            continue
        D = {**(D or {}), **Dx}
    if D:
        P("## Dense speed grid (3-30 m/s every 0.25 m/s): turn-hold, s02 tracking, dwell-then-jump, per member")
        P("")
        P("| column | member | turn-hold min >= 8 (v) | s02 gain min / max >= 8 (v) | dj events 3-7 / 7.25-13 / 13.25-30 | "
          "stick % max 3-7 | hold slips 13.25-30 |")
        P("|---|---|---|---|---|---|---|")
        for j, lab in enumerate(labs_d):
            for mem in [m for m in ("nominal", "bc", "nominal+h10", "F_hi") if any(k[2] == m for k in D)]:
                rh = [(v, D[(n, v, m)]) for (n, v, m) in D if n == "rh" and m == mem]
                s02 = [(v, D[(n, v, m)]) for (n, v, m) in D if n == "s02" and m == mem]
                hv = min(((x["hold_ratio"][j], v) for v, x in rh if v >= 7.9))
                gmin = min(((x["track_gain"][j], v) for v, x in s02 if v >= 7.9))
                gmax = max(((x["track_gain"][j], v) for v, x in s02 if v >= 7.9))

                def djb(lo, hi):
                    return sum(D[(n, v, m)]["dj_events"][j] for (n, v, m) in D if n in ("s02", "ssm") and m == mem
                               and lo <= v <= hi)
                stk = max(D[(n, v, m)]["stick_pct"][j] for (n, v, m) in D if n in ("s02", "ssm") and m == mem and v <= 7)
                hs = sum(x["hold_slips"][j] for v, x in rh if v >= 13.25)
                P(f"| {lab} | {mem} | {hv[0]:.3f} ({hv[1]:g}) | {gmin[0]:.3f} ({gmin[1]:g}) / {gmax[0]:.3f} ({gmax[1]:g}) | "
                  f"{djb(0, 7):.0f} / {djb(7.25, 13):.0f} / {djb(13.25, 31):.0f} | {stk:.1f} | {hs:.0f} |")
        P("")
    (R.HERE / "score_time_out.md").write_text("\n".join(L) + "\n", encoding="utf-8")
    (R.OUT / "time_verdict.json").write_text(json.dumps(verdict))
    print("\n".join(L[:12]))


if __name__ == "__main__":
    main()
