#!/usr/bin/env python3
"""loop_op_lib -- the COMMAND <-> RESPONSE CAUSALITY instrument.

Question it exists to answer (V85 session, 2026-08-08): does the 18-22 Hz / 26-31 Hz content on the
torsion bar close a loop THROUGH OPENPILOT, or is openpilot's command an echo of a loop that closes
entirely inside the EPS + plant?  `docs/STATE.md` (V80 block) flags the exact missing measurement:

    "correlated +0.93 at lag 0 with the bar; bar/command ratio at 27 Hz is 15.8x.  [BELIEF] an echo,
     not a cause ... Settling it needs a phase-resolved coherence, not the lag-0 correlation."

===================================================================================================
THE INSTRUMENT DECISION, AND WHY IT DIFFERS FROM EVERY PRIOR CACHE IN THIS KIT   [EVIDENCE]
===================================================================================================
Measured on route 6d seg 5 by `probe/loop_op_probe.py`:

    age of newest 0x18F        at each 0x14A:  mean 0.37 ms   p50 0.00   p95 0.00
    age of newest can129 0x0E4 at each 0x14A:  mean 0.02 ms   p50 0.00   p95 0.00
    age of newest sendcan 0x0E4 at each 0x14A: mean 6.54 ms   p50 6.46   p95 7.59

=> the panda's `can` service publishes ONE BATCH per ~10 ms read, and **every frame inside a batch
carries the SAME logMonoTime**.  There is no sub-frame arrival resolution in `can` at all.  Two
consequences, both load-bearing:

 (1) The "0x18F is one frame (9.9 ms) stale vs 0x14A" calibration
     (`memory/accord/signals/accord-0x18f-payload-one-frame-stale.md`) is a property of the CACHE EXTRACTOR, not of
     the bus: `extract66` builds one row per 0x14A frame and carries `last18` forward, and 0x18F
     happens to sit AFTER 0x14A in the batch's message list, so the held value is a whole batch old.
     Indexing by BATCH instead of by 0x14A-frame removes it structurally -- there is nothing left to
     correct.  `TAU_18F` is retained as a settable knob so any claim here can be re-run with the
     legacy +9.9 ms applied and price its own sensitivity.

 (2) The command must be taken from **`can` src129 0x0E4** -- the panda's TX-completion echo of the
     frame openpilot sent -- and NOT from `sendcan`.  The echo rides the SAME batch stream as the
     bar, so command and response share one clock exactly.  `sendcan`'s own logMonoTime sits
     6.52 +/- 0.6 ms earlier (openpilot publish -> panda TX -> bus -> panda RX -> batch publish) and
     interpolating it onto a foreign lattice injects a fractional-delay filter whose group delay
     drifts with the comma/car clock beat.  The echo is value-identical to the newest `sendcan`
     payload on **99.97%** of frames, so nothing is lost by using it.
     `sendcan` is still extracted, with its own timestamps, purely as a cross-check.

RESIDUAL, UNMEASURED LATENCIES AND WHICH WAY THEY BIAS THE ANSWER   [EVIDENCE on the sign]
    unknown A: bus arrival -> EPS latches the command                        >= 0
    unknown B: EPS samples the bar -> EPS transmits 0x18F                    >= 0
    Both make the RESPONSE appear LATER relative to the COMMAND than it physically is, i.e. both
    inflate the measured cmd->bar group delay in the POSITIVE ("command is driving") direction.
    => a measured NEGATIVE delay (bar LEADS command) is CONSERVATIVE evidence for "echo".
       A measured positive delay is NOT conservative and must be compared against the sum of the
       plausible actuator lags before it is read as "driving".

===================================================================================================
SIGN AND SCALE OF THE CHANNELS
===================================================================================================
    cmd     0x0E4 bytes 0-1, i16be, RAW COUNTS, as transmitted on bus 1.  openpilot's STEER_TORQUE
            request.  Rails: +/-4096 amplitude, 123 counts/frame slew (`docs/STATE.md` L1288).
    bar     0x18F bytes 0-1, i16be * -1.0, counts, LSB = 8 counts.  Torsion bar (STEER_TORQUE_SENSOR)
            -- the SAME channel every prior route in this corpus calls `tq`, same sign.
    ang     0x14A bytes 0-1, i16be * -0.1, deg      rate_c  0x14A bytes 2-3, i16be * -1.0, deg/s
    cam     0x0E4 on bus 2, i16be -- the STOCK camera's own command.  A control channel: it is
            generated by hardware that cannot see the bar, so its coherence with the bar is a
            genuine null for "any 0x0E4-shaped signal correlates with the bar".

    🛑 The cmd/bar SIGN CONVENTION is not asserted here.  `bar` carries the corpus's -1.0 factor and
    `cmd` is raw, so the transfer's absolute phase has an unresolved 180 deg ambiguity.  Every claim
    in this module is built on the phase SLOPE (group delay), which is immune to it, or on
    coherence, which is immune to it.  Absolute phase is reported but never load-bearing.

===================================================================================================
EPISODES AND THE STATISTICAL BAR (pre-registered)
===================================================================================================
    Bendat-Piersol: relative sd of |H| = sqrt((1-g2)/(2*K*g2)).
    A decision-bearing transfer claim needs g2 >= 0.8 over K >= 10 non-overlapping EPISODES.
    REFUSE below g2 = 0.5.  Significance floor g2_crit = 1 - 0.05**(1/(K-1)).
    Bootstrap over EPISODES, never windows (`memory/feedback-episodes-not-windows`).
    Trustworthy: DC-40 Hz magnitude, DC-25 Hz phase.  27.5 Hz is at the EDGE of phase validity.
"""
# --- PATH BOOTSTRAP (repo reorg 2026-08-26; MULTI-ROOT FIX 2026-08-26) ----
# These files import sibling modules by bare name.  The kit has MORE THAN ONE
# import root (each marked by a `.pkgroot` file): `analysis-2020accord/` and
# `rlog-tools/`.  The original block stopped at the FIRST `.pkgroot` above the
# file, so a `rlog-tools/` script could not see `analysis-2020accord/lib/` and
# the whole extractor family died with `ModuleNotFoundError: _grind2_lib`.
# Fix: put EVERY kit root in the repo, and every code subfolder under each, on
# sys.path -- nearest root first, so local modules still win.
import os as _os, sys as _sys
_r = _os.path.dirname(_os.path.abspath(__file__))
while not _os.path.isfile(_os.path.join(_r, ".pkgroot")):
    _n = _os.path.dirname(_r)
    if _n == _r:
        raise RuntimeError("no .pkgroot marker above " + __file__)
    _r = _n
_repo = _r
while not _os.path.isdir(_os.path.join(_repo, ".git")):
    _n = _os.path.dirname(_repo)
    if _n == _repo:
        _repo = None
        break
    _repo = _n
_roots = [_r]
if _repo:
    for _e in sorted(_os.listdir(_repo)):
        _d = _os.path.join(_repo, _e)
        if _d != _r and _os.path.isfile(_os.path.join(_d, ".pkgroot")):
            _roots.append(_d)
_p = []
for _root in _roots:
    _p.append(_root)
    for _b, _ds, _fs in _os.walk(_root):
        _ds[:] = [_x for _x in _ds if not _x.startswith((".", "_")) and _x not in
                  ("rlogs", "ghidra_project", "__pycache__", "reference/opendbc")]
        _p.extend(_os.path.join(_b, _x) for _x in _ds)
_sys.path[:0] = [_x for _x in _p if _x not in _sys.path]
for _v in ("_os", "_sys", "_r", "_n", "_repo", "_roots", "_p", "_root",
           "_b", "_ds", "_fs", "_e", "_d", "_x", "_v"):
    globals().pop(_v, None)
# --- end path bootstrap ---------------------------------------------------
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parents[1]
ROOT = HERE.parent
sys.path.insert(0, str(HERE))

RLOGDIR = ROOT / "analysis-2020accord" / "rlogs"
CACHE = ROOT / "_scratch/cache/loop_op"

ROUTES = {
    "V84/r6d":  ("75604b0a432fdc89_0000006d--5d03a5adb4", 12),
    "V83a/r68": ("75604b0a432fdc89_00000068--0b7efae911", 8),
    "V81/r67":  ("75604b0a432fdc89_00000067--9b3ebbe218", 14),
    "V80/r66":  ("75604b0a432fdc89_00000066--276b942769", 15),
}

# --- analysis constants -------------------------------------------------------------------------
NPERSEG = 512          # 5.12 s @100 Hz -> 0.195 Hz bins
EP_MAX = 2048          # 20.48 s episode cap
LATTICE_GAP = 0.015    # s
TAU_18F = 0.0          # 🛑 ZERO by construction here -- see the module docstring, point (1).
STEER_MAX = 4096.0
SLEW_CAP = 123.0       # counts/frame = 0.03 * STEER_MAX

# 🛑 `0.4-2` is the SIGN ANCHOR, not a symptom band.  Below ~2 Hz the loop is dominated by
# openpilot's exogenous lane demand (Srr >> Sdd), so H1 -> G there, and an 18 ms delay is only 13 deg
# -- small enough that the measured phase resolves the 180 deg ambiguity between the corpus's
# negated `bar`/`ang` and the raw `cmd`.  Every absolute-phase reading elsewhere is referred to it.
BANDS = {"0.4-2": (0.4, 2.0), "2-5": (2.0, 5.0), "6-9": (6.0, 9.0), "10-16": (10.0, 16.0),
         "18-22": (18.0, 22.0), "26-31": (26.0, 31.0), "32-38": (32.0, 38.0), "40-49": (40.0, 49.0)}


def i16be(d, i):
    v = (d[i] << 8) | d[i + 1]
    return v - 0x10000 if v & 0x8000 else v


# ============================================================================ extraction =========
def extract_segment(path):
    """One rlog.zst -> per-BATCH arrays PLUS per-frame NATIVE sequences.

    The batch grid is convenient (all channels aligned, one row per ~10 ms) and is what the
    time-domain tests use.  But the panda's ~100 Hz read and the EPS's ~100 Hz transmit BEAT, so a
    few percent of batches carry two copies of a frame and the next carries none -- up to 13% of
    `bar` on some segments.  Forward-filling that is a time-varying sample-and-hold and it is NOT
    the same pattern on the command channel, so it would bias a 27 Hz phase measurement.
    The NATIVE sequences (`n18_*`, `n14_*`, `ne4_*`) keep every frame in arrival order, which IS
    the transmitter's own uniform lattice; `native_block` below turns them into exact-phase spectra
    with no interpolation anywhere.
    """
    from rlog_parse import read_messages

    bt, bar, mot, b18_4, ang, rate_c, wang, p14, cmd, creq, cam = ([] for _ in range(11))
    n18_t, n18_bar, n18_mot, n18_b4 = [], [], [], []
    n14_t, n14_ang, n14_rate, n14_p14 = [], [], [], []
    ne4_t, ne4_cmd, ne4_req = [], [], []
    sc_t, sc_v, sc_r = [], [], []
    cc_t, cc_lat, cc_en, cc_rq = [], [], [], []
    cs_t, cs_v, cs_pr, cs_ang = [], [], [], []

    for evt in read_messages(path):
        try:
            w = evt.which()
        except Exception:
            continue
        tm = evt.logMonoTime * 1e-9
        if w == "can":
            g = dict(bar=np.nan, mot=np.nan, b4=np.nan, ang=np.nan, rate=np.nan, wang=np.nan,
                     p14=np.nan, cmd=np.nan, creq=np.nan, cam=np.nan)
            for m in evt.can:
                src, addr = int(m.src), int(m.address)
                d = bytes(m.dat)
                if src == 1 and addr == 0x18F and len(d) >= 5:
                    g["bar"] = i16be(d, 0) * -1.0
                    g["mot"] = float(i16be(d, 2))
                    g["b4"] = float(d[4])
                    n18_t.append(tm); n18_bar.append(g["bar"])
                    n18_mot.append(g["mot"]); n18_b4.append(g["b4"])
                elif src == 1 and addr == 0x14A and len(d) >= 7:
                    g["ang"] = i16be(d, 0) * -0.1
                    g["rate"] = i16be(d, 2) * -1.0
                    g["wang"] = i16be(d, 5) * -0.1
                    g["p14"] = float(d[4])
                    n14_t.append(tm); n14_ang.append(g["ang"])
                    n14_rate.append(g["rate"]); n14_p14.append(g["p14"])
                elif src == 129 and addr == 0x0E4 and len(d) >= 3:
                    g["cmd"] = float(i16be(d, 0))
                    g["creq"] = float((d[2] >> 7) & 1)
                    ne4_t.append(tm); ne4_cmd.append(g["cmd"]); ne4_req.append(g["creq"])
                elif src == 2 and addr == 0x0E4 and len(d) >= 3:
                    g["cam"] = float(i16be(d, 0))
            if np.isnan(g["ang"]) and np.isnan(g["bar"]) and np.isnan(g["cmd"]):
                continue
            bt.append(tm)
            bar.append(g["bar"]); mot.append(g["mot"]); b18_4.append(g["b4"])
            ang.append(g["ang"]); rate_c.append(g["rate"]); wang.append(g["wang"])
            p14.append(g["p14"]); cmd.append(g["cmd"]); creq.append(g["creq"]); cam.append(g["cam"])
        elif w == "sendcan":
            for m in evt.sendcan:
                if int(m.src) == 1 and int(m.address) == 0x0E4:
                    d = bytes(m.dat)
                    if len(d) >= 3:
                        sc_t.append(tm); sc_v.append(float(i16be(d, 0)))
                        sc_r.append(float((d[2] >> 7) & 1))
        elif w == "carControl":
            c = evt.carControl
            cc_t.append(tm); cc_lat.append(float(bool(c.latActive)))
            cc_en.append(float(bool(c.enabled)))
            try:
                cc_rq.append(float(c.actuators.torque))
            except Exception:
                cc_rq.append(np.nan)
        elif w == "carState":
            c = evt.carState
            cs_t.append(tm); cs_v.append(float(c.vEgo))
            cs_pr.append(float(bool(c.steeringPressed)))
            cs_ang.append(float(c.steeringAngleDeg))

    d = dict(t=np.array(bt), bar=np.array(bar), mot=np.array(mot), b18_4=np.array(b18_4),
             ang=np.array(ang), rate_c=np.array(rate_c), wang=np.array(wang),
             p14=np.array(p14), cmd=np.array(cmd), creq=np.array(creq), cam=np.array(cam),
             sc_t=np.array(sc_t), sc_v=np.array(sc_v), sc_r=np.array(sc_r),
             n18_t=np.array(n18_t), n18_bar=np.array(n18_bar), n18_mot=np.array(n18_mot),
             n18_b4=np.array(n18_b4),
             n14_t=np.array(n14_t), n14_ang=np.array(n14_ang), n14_rate=np.array(n14_rate),
             n14_p14=np.array(n14_p14),
             ne4_t=np.array(ne4_t), ne4_cmd=np.array(ne4_cmd), ne4_req=np.array(ne4_req))
    # slow services: zero-order hold onto the batch lattice (they are all <= 20 Hz content)
    for nm, tt, vv in (("cc_lat", cc_t, cc_lat), ("cc_en", cc_t, cc_en), ("cc_rq", cc_t, cc_rq),
                       ("cs_v", cs_t, cs_v), ("cs_pr", cs_t, cs_pr), ("cs_ang", cs_t, cs_ang)):
        tt, vv = np.asarray(tt, float), np.asarray(vv, float)
        d[nm] = (np.interp(d["t"], tt, vv) if len(tt) > 1
                 else np.full(len(d["t"]), np.nan))
    return d


def hold_fill(x):
    """Forward-fill NaNs (a batch that happened to carry no copy of that frame), then back-fill the
    leading run.  Returns (filled, n_filled)."""
    x = np.asarray(x, float).copy()
    bad = ~np.isfinite(x)
    if bad.all():
        return x, int(bad.sum())
    idx = np.where(~bad, np.arange(len(x)), 0)
    np.maximum.accumulate(idx, out=idx)
    x = x[idx]
    first = np.flatnonzero(~bad)[0]
    x[:first] = x[first]
    return x, int(bad.sum())


def fs_lattice(t):
    """(n-1)/span over the longest gap-free stretch.  🛑 NEVER 1/median(dt)."""
    t = np.asarray(t, float)
    if len(t) < 3:
        return 100.0
    dt = np.diff(t)
    brk = np.flatnonzero(dt > 0.05)
    edges = [0] + list(brk + 1) + [len(t)]
    a, b = max(zip(edges[:-1], edges[1:]), key=lambda ab: ab[1] - ab[0])
    if b - a < 3 or t[b - 1] <= t[a]:
        return float(1.0 / np.median(dt))
    return float((b - a - 1) / (t[b - 1] - t[a]))


def build_route(route, verbose=True):
    stem, nseg = ROUTES[route]
    out = []
    for s in range(nseg):
        p = RLOGDIR / f"{stem}--{s}--rlog.zst"
        if not p.exists():
            continue
        d = extract_segment(p)
        if len(d["t"]) < 100:
            continue
        nf = {}
        for k in ("bar", "mot", "b18_4", "ang", "rate_c", "wang", "p14", "cmd", "creq", "cam"):
            d[k], nf[k] = hold_fill(d[k])
        d["_fs"] = fs_lattice(d["t"])
        d["_seg"] = s
        d["_route"] = route
        d["_nfill"] = nf
        if verbose:
            eng = np.mean(d["cc_lat"] > 0.5) * 100
            print(f"  {route} seg{s:2d}: n={len(d['t']):5d}  fs={d['_fs']:.4f}  "
                  f"eng={eng:5.1f}%  v={np.nanmean(d['cs_v']):5.2f}  "
                  f"fill(bar/cmd)={nf['bar']}/{nf['cmd']}", flush=True)
        out.append(d)
    return out


def save_route(route, segs):
    CACHE.mkdir(parents=True, exist_ok=True)
    tag = route.split("/")[1]
    for d in segs:
        np.savez_compressed(CACHE / f"loopop_{tag}_s{d['_seg']}.npz",
                            **{k: v for k, v in d.items() if isinstance(v, np.ndarray)},
                            _fs=np.array([d["_fs"]]), _seg=np.array([d["_seg"]]),
                            _route=np.array([route]))


def load_route(route):
    tag = route.split("/")[1]
    out = []
    for p in sorted(CACHE.glob(f"loopop_{tag}_s*.npz"),
                    key=lambda q: int(q.stem.split("_s")[-1])):
        z = np.load(p, allow_pickle=False)
        d = {k: z[k] for k in z.files}
        d["_fs"] = float(d["_fs"][0])
        d["_seg"] = int(d["_seg"][0])
        d["_route"] = route
        out.append(d)
    return out


# ============================================================================ masks ==============
def mask_engaged(d):
    return (d["cc_lat"] > 0.5) & (d["creq"] > 0.5)


def mask_manual(d):
    return (d["cc_lat"] < 0.5) & (np.abs(d["cs_v"]) > 1.0)


def lattice_ok(d):
    t = np.asarray(d["t"], float)
    ok = np.ones(len(t), bool)
    ok[1:] = np.diff(t) < LATTICE_GAP
    return ok


def episodes(d, mask, nperseg=NPERSEG, ep_max=EP_MAX):
    """Maximal lattice-contiguous runs of `mask`, split at `ep_max`, truncated to whole blocks."""
    m = np.asarray(mask, bool) & lattice_ok(d)
    idx = np.flatnonzero(m)
    if not len(idx):
        return
    starts, ends = [idx[0]], []
    for a, b in zip(idx[:-1], idx[1:]):
        if b != a + 1:
            ends.append(a + 1)
            starts.append(b)
    ends.append(idx[-1] + 1)
    for s, e in zip(starts, ends):
        while e - s >= nperseg:
            n = min(ep_max, e - s)
            n -= n % nperseg
            yield (s, s + n)
            s += n


# ====================================================== NATIVE-LATTICE (exact-phase) spectra =====
# 🛑 THIS IS THE PATH EVERY PHASE / GROUP-DELAY CLAIM IS BUILT ON.  No interpolation anywhere.
#
# Each transmitter (the EPS for 0x18F and 0x14A, openpilot for 0x0E4) emits on its OWN uniform
# ~100 Hz lattice.  The panda's batch timestamp quantises arrival to +/-5 ms, but a straight-line
# fit of batch-time vs frame-index over thousands of frames averages that jitter down to well under
# 0.1 ms, recovering the transmitter's lattice:      t_c(k) = a_c + b_c * k
# A block of N frames starting at index k0 is then a UNIFORM sample record whose absolute start
# time is known.  Its DFT is referred to a common epoch by  X_j *= exp(-j*2*pi*f_j*(t_c(k0)-T_ref)),
# which is an EXACT phase correction -- unlike `np.interp` onto a foreign grid, whose group delay
# is a fraction of a frame that drifts with the comma/car clock beat (0-10 ms = 0-97 deg at 27 Hz).
NATIVE = {"bar": ("n18_t", "n18_bar"), "mot": ("n18_t", "n18_mot"), "b18_4": ("n18_t", "n18_b4"),
          "ang": ("n14_t", "n14_ang"), "rate_c": ("n14_t", "n14_rate"),
          "p14": ("n14_t", "n14_p14"),
          "cmd": ("ne4_t", "ne4_cmd"), "creq": ("ne4_t", "ne4_req"),
          "sc_cmd": ("sc_t", "sc_v")}


def lattice_fit(t):
    """(a, b, rms_resid_ms, n) for t[k] ~ a + b*k, ordinary LS over the whole run."""
    t = np.asarray(t, float)
    n = len(t)
    k = np.arange(n, dtype=float)
    b, a = np.polyfit(k, t, 1)
    resid = t - (a + b * k)
    return float(a), float(b), float(np.std(resid) * 1e3), n


def native_meta(d):
    """Per-channel lattice fit + the fs mismatch that limits the phase accuracy."""
    out = {}
    for ch, (tk, vk) in NATIVE.items():
        if tk not in d or len(d[tk]) < 100:
            continue
        a, b, rms, n = lattice_fit(d[tk])
        out[ch] = dict(a=a, b=b, fs=1.0 / b, jit_ms=rms, n=n)
    return out


def native_block(d, ch, t_start, nperseg, meta=None):
    """(X, f, t_actual) for one Hann-windowed, detrended block of channel `ch` beginning at the
    first native sample at or after `t_start`.  Returns None if the block runs off the end or
    crosses a lattice gap > 15 ms.

    🛑 The lattice fit is LOCAL TO THE BLOCK, not global to the segment.  A whole-segment fit is
    destroyed by any pause in the log -- measured: it drags the apparent 0x18F rate to 99.56 Hz and
    the fit residual to 23 ms on route 6d, which would be a 196 deg epoch error at 27 Hz.  A block
    that survives the >15 ms gap test is on a clean lattice by construction, so its own 512-point
    LS fit is exact: with ~1 ms per-sample timestamp jitter the intercept sd is 1/sqrt(512) =
    0.04 ms and the block-end slope error is ~0.15 ms.  Both are negligible at 27 Hz.
    """
    tk, vk = NATIVE[ch]
    t, v = np.asarray(d[tk], float), np.asarray(d[vk], float)
    if len(t) < nperseg + 2:
        return None
    k0 = int(np.searchsorted(t, t_start, side="left"))
    if k0 + nperseg > len(t):
        return None
    seg_t = t[k0:k0 + nperseg]
    if np.max(np.diff(seg_t)) > LATTICE_GAP:
        return None
    x = v[k0:k0 + nperseg]
    if not np.all(np.isfinite(x)):
        return None
    r = np.arange(nperseg, dtype=float)
    b, a = np.polyfit(r, seg_t, 1)          # local lattice: t[k0+i] ~ a + b*i
    x = x - np.polyval(np.polyfit(r, x, 1), r)
    X = np.fft.rfft(x * np.hanning(nperseg))
    f = np.fft.rfftfreq(nperseg, b)
    return X, f, a


def native_spectra(d, t0, t1, xch, ykey_ch, nperseg=NPERSEG, hop_s=None):
    """Averaged auto/cross spectra of (xch, ych) over [t0, t1] wall-clock, exact relative phase.

    Blocks are laid out on WALL CLOCK (both channels get the same requested start time), then each
    channel's exact block-start time is used to refer its DFT to that requested epoch.
    Sxy = conj(X)*Y  =>  H1 = Sxy/Sxx and arg(Sxy) = arg(Y) - arg(X).
    """
    meta = None
    for ch in (xch, ykey_ch):
        tk, _ = NATIVE[ch]
        if tk not in d or len(d[tk]) < nperseg + 2:
            return None
    dur = nperseg / 100.0
    hop = dur / 2 if hop_s is None else hop_s
    f_ref = None
    Sxx = Syy = Sxy = None
    n = 0
    ts = t0
    while ts + dur <= t1:
        bx = native_block(d, xch, ts, nperseg, meta)
        by = native_block(d, ykey_ch, ts, nperseg, meta)
        ts += hop
        if bx is None or by is None:
            continue
        X, fx, tx = bx
        Y, fy, ty = by
        if f_ref is None:
            f_ref = 0.5 * (fx + fy)
            Sxx = np.zeros(len(f_ref)); Syy = np.zeros(len(f_ref))
            Sxy = np.zeros(len(f_ref), complex)
        # refer both to the requested epoch `ts - hop`
        X = X * np.exp(-1j * 2 * np.pi * fx * (tx - (ts - hop)))
        Y = Y * np.exp(-1j * 2 * np.pi * fy * (ty - (ts - hop)))
        Sxx += np.abs(X) ** 2
        Syy += np.abs(Y) ** 2
        Sxy += np.conj(X) * Y
        n += 1
    if not n:
        return None
    return f_ref, Sxx / n, Syy / n, Sxy / n, n


def native_episodes(d, mask, nperseg=NPERSEG, ep_max=EP_MAX):
    """Episode (t0, t1) wall-clock windows from a mask defined on the BATCH grid."""
    for i0, i1 in episodes(d, mask, nperseg, ep_max):
        yield float(d["t"][i0]), float(d["t"][i1 - 1])


def collect_native(route, mask_fn, xch="cmd", ych="bar", nperseg=NPERSEG, ep_max=EP_MAX,
                   extra=None, segs=None):
    out = []
    for d in (segs if segs is not None else load_route(route)):
        m = mask_fn(d)
        for t0, t1 in native_episodes(d, m, nperseg, ep_max):
            r = native_spectra(d, t0, t1, xch, ych, nperseg)
            if r is None or r[4] < 2:
                continue
            f, Sxx, Syy, Sxy, nb = r
            i0 = int(np.searchsorted(d["t"], t0)); i1 = int(np.searchsorted(d["t"], t1))
            v = np.abs(np.asarray(d["cs_v"], float)[i0:i1 + 1])
            rec = dict(f=f, Sxx=Sxx, Syy=Syy, Sxy=Sxy, nblk=nb, route=route, seg=int(d["_seg"]),
                       i0=i0, i1=i1, t0=t0, t1=t1, sec=t1 - t0, fs=d["_fs"],
                       v_mean=float(v.mean()), v_p5=float(np.percentile(v, 5)),
                       v_p95=float(np.percentile(v, 95)))
            if extra is not None:
                rec.update(extra(d, i0, i1))
            out.append(rec)
    return out


# ============================================================================ spectra ============
def ep_spectra(d, i0, i1, xkey, ykey, nperseg=NPERSEG, hop=None, tau=0.0, xscale=1.0, yscale=1.0):
    """Within-episode averaged auto/cross spectra of (x, y).  Sxy = conj(X)*Y  =>  H1 = Sxy/Sxx.

    `tau` rotates Y by exp(+j*w*tau) -- i.e. it treats Y as `tau` seconds STALE.  Zero here by
    construction (batch indexing); exposed so a claim can be re-run under the legacy +9.9 ms.
    """
    hop = nperseg // 2 if hop is None else hop
    fs = d["_fs"]
    xa = np.asarray(d[xkey], float) * xscale
    ya = np.asarray(d[ykey], float) * yscale
    w = np.hanning(nperseg)
    f = np.fft.rfftfreq(nperseg, 1 / fs)
    rot = np.exp(1j * 2 * np.pi * f * tau)
    r = np.arange(nperseg, dtype=float)
    Sxx = np.zeros(len(f)); Syy = np.zeros(len(f)); Sxy = np.zeros(len(f), complex)
    n = 0
    for i in range(i0, i1 - nperseg + 1, hop):
        x, y = xa[i:i + nperseg], ya[i:i + nperseg]
        if not (np.all(np.isfinite(x)) and np.all(np.isfinite(y))):
            continue
        x = x - np.polyval(np.polyfit(r, x, 1), r)
        y = y - np.polyval(np.polyfit(r, y, 1), r)
        X = np.fft.rfft(x * w)
        Y = np.fft.rfft(y * w) * rot
        Sxx += np.abs(X) ** 2
        Syy += np.abs(Y) ** 2
        Sxy += np.conj(X) * Y
        n += 1
    if not n:
        return f, None, None, None, 0
    return f, Sxx / n, Syy / n, Sxy / n, n


def collect(route, mask_fn, xkey="cmd", ykey="bar", nperseg=NPERSEG, tau=0.0,
            ep_max=EP_MAX, extra=None, segs=None):
    out = []
    for d in (segs if segs is not None else load_route(route)):
        for i0, i1 in episodes(d, mask_fn(d), nperseg, ep_max):
            f, Sxx, Syy, Sxy, nb = ep_spectra(d, i0, i1, xkey, ykey, nperseg, tau=tau)
            if nb < 2:
                continue
            v = np.abs(np.asarray(d["cs_v"], float)[i0:i1])
            rec = dict(f=f, Sxx=Sxx, Syy=Syy, Sxy=Sxy, nblk=nb, route=route, seg=int(d["_seg"]),
                       i0=int(i0), i1=int(i1), sec=(i1 - i0) / d["_fs"], fs=d["_fs"],
                       v_mean=float(v.mean()), v_p5=float(np.percentile(v, 5)),
                       v_p95=float(np.percentile(v, 95)))
            if extra is not None:
                rec.update(extra(d, i0, i1))
            out.append(rec)
    return out


def stack(recs):
    if not recs:
        return None, None, None, None, 0
    f = recs[0]["f"]
    wgt = np.array([r["nblk"] for r in recs], float)
    Sxx = np.tensordot(wgt, np.array([r["Sxx"] for r in recs]), 1) / wgt.sum()
    Syy = np.tensordot(wgt, np.array([r["Syy"] for r in recs]), 1) / wgt.sum()
    Sxy = np.tensordot(wgt, np.array([r["Sxy"] for r in recs]), 1) / wgt.sum()
    return f, Sxx, Syy, Sxy, len(recs)


def coh(Sxx, Syy, Sxy):
    with np.errstate(divide="ignore", invalid="ignore"):
        return np.abs(Sxy) ** 2 / (Sxx * Syy)


def g2_crit(K, alpha=0.05):
    """Significance floor for magnitude-squared coherence with K independent averages."""
    return 1.0 - alpha ** (1.0 / max(K - 1, 1))


def bp_sd(g2, K):
    """Bendat-Piersol relative sd of |H| (and, in rad, the sd of arg H)."""
    g2 = np.clip(g2, 1e-9, 1 - 1e-9)
    return np.sqrt((1 - g2) / (2 * K * g2))


# ============================================================================ group delay ========
def band_delay(f, Sxy, lo, hi, wgt=None):
    """Group delay over [lo,hi] from a WEIGHTED least-squares fit of unwrapped arg(Sxy) vs f.

    Returns (tau_s, phi0_deg, r2, n).  tau > 0 means Y LAGS X (X leads => X could be driving Y).
    Sign convention: Sxy = conj(X)*Y, so arg(Sxy) = arg(Y) - arg(X);  a pure delay
    y(t) = x(t - tau) gives arg = -w*tau  =>  slope d(arg)/df = -2*pi*tau.
    """
    sel = (f >= lo) & (f <= hi)
    ff = f[sel]
    if sel.sum() < 3:
        return np.nan, np.nan, np.nan, int(sel.sum())
    ph = np.unwrap(np.angle(Sxy[sel]))
    w = np.ones(sel.sum()) if wgt is None else np.nan_to_num(wgt[sel], nan=0.0, posinf=0.0)
    if w.sum() <= 0:
        return np.nan, np.nan, np.nan, int(sel.sum())
    W = w / w.sum()
    fm, pm = np.sum(W * ff), np.sum(W * ph)
    cov = np.sum(W * (ff - fm) * (ph - pm))
    var = np.sum(W * (ff - fm) ** 2)
    if var <= 0:
        return np.nan, np.nan, np.nan, int(sel.sum())
    slope = cov / var
    pred = pm + slope * (ff - fm)
    ss = np.sum(W * (ph - pred) ** 2)
    st = np.sum(W * (ph - pm) ** 2)
    return (float(-slope / (2 * np.pi)), float(np.degrees(pm - slope * fm)),
            float(1 - ss / st) if st > 0 else np.nan, int(sel.sum()))


def band_stats(f, Sxx, Syy, Sxy, lo, hi, K):
    """Band-aggregated coherence, |H|, phase, delay.  Bins are SUMMED before the ratio -- the
    Bendat-Piersol band-averaged estimator, not a mean of per-bin ratios."""
    sel = (f >= lo) & (f <= hi)
    sxx, syy = float(Sxx[sel].sum()), float(Syy[sel].sum())
    sxy = complex(Sxy[sel].sum())
    if sxx <= 0 or syy <= 0:
        return dict(lo=lo, hi=hi, g2=np.nan, H=np.nan, ph=np.nan, tau_ms=np.nan, r2=np.nan,
                    rms_x=np.nan, rms_y=np.nan, ratio=np.nan, nbin=int(sel.sum()), K=K)
    g2 = abs(sxy) ** 2 / (sxx * syy)
    H = abs(sxy) / sxx
    w = coh(Sxx, Syy, Sxy) * Sxx
    tau, ph0, r2, _ = band_delay(f, Sxy, lo, hi, wgt=w)
    return dict(lo=lo, hi=hi, g2=float(g2), H=float(H), ph=float(np.degrees(np.angle(sxy))),
                tau_ms=float(tau * 1e3), r2=r2, rms_x=float(np.sqrt(sxx)),
                rms_y=float(np.sqrt(syy)), ratio=float(np.sqrt(syy / sxx)),
                nbin=int(sel.sum()), K=K, g2crit=g2_crit(K), sd_H=float(bp_sd(g2, K)))


def boot_band(recs, lo, hi, nboot=2000, seed=8585):
    """Episode bootstrap of `band_stats`.  Resamples EPISODES with replacement -- never windows."""
    rng = np.random.default_rng(seed)
    f, Sxx, Syy, Sxy, K = stack(recs)
    if K == 0:
        return None, {}
    pt = band_stats(f, Sxx, Syy, Sxy, lo, hi, K)
    if K < 4:
        return pt, {k: (np.nan, np.nan) for k in ("g2", "H", "tau_ms", "ratio")}
    keys = ("g2", "H", "tau_ms", "ratio", "ph")
    smp = {k: [] for k in keys}
    n = len(recs)
    for _ in range(nboot):
        j = rng.integers(0, n, n)
        f2, sx, sy, sc, _ = stack([recs[i] for i in j])
        r = band_stats(f2, sx, sy, sc, lo, hi, K)
        for k in keys:
            smp[k].append(r[k])
    ci = {k: (float(np.nanpercentile(smp[k], 2.5)), float(np.nanpercentile(smp[k], 97.5)))
          for k in keys}
    return pt, ci


# ============================================================================ nulls ==============
def mismatch_null(recs, shift=1, seed=4242):
    """Coherence floor from PHASE-RANDOMISED episode pairing.  Exactly 1/K in expectation."""
    K = len(recs)
    if K < 3:
        return None, 0
    rng = np.random.default_rng(seed)
    f = recs[0]["f"]
    Sxx = np.mean([r["Sxx"] for r in recs], axis=0)
    Syy = np.mean([r["Syy"] for r in recs], axis=0)
    acc = np.zeros(len(f), complex)
    for i, r in enumerate(recs):
        o = recs[(i + shift) % K]
        ph = rng.uniform(0, 2 * np.pi, len(f))
        acc += np.sqrt(r["Sxx"] * o["Syy"]) * np.exp(1j * ph)
    return coh(Sxx, Syy, acc / K), K


def fill_mask(d, ch="bar"):
    """True where the BATCH GRID value of `ch` is a forward-fill (no frame arrived in that batch).

    The panda's ~100 Hz read and the transmitter's ~100 Hz cadence beat, so a few percent of
    batches carry two copies of a frame and the next carries none -- up to 13% of `bar` on some
    segments.  Native-lattice spectra are immune; TIME-DOMAIN tests (Granger, envelopes, edges)
    are not, because a repeated sample is an artificial one-lag autocorrelation.  Detect it
    exactly: a batch is a fill iff its timestamp appears in no native frame timestamp.
    """
    tk = {"bar": "n18_t", "mot": "n18_t", "ang": "n14_t", "rate_c": "n14_t",
          "cmd": "ne4_t", "creq": "ne4_t"}[ch]
    return ~np.isin(np.asarray(d["t"], float), np.asarray(d[tk], float))


def fmt_ci(pt, ci, sf=3):
    lo, hi = ci
    return f"{pt:.{sf}g} [{lo:.{sf}g}, {hi:.{sf}g}]"
