# -*- coding: utf-8 -*-
"""studies/grind/adv_v290_relocation.py -- THE DECIDING MEASUREMENT for the V290 adversarial pass: V289 moved the line
from 20 Hz to ~16.5 Hz, engaged-only; re-fit the plant to BOTH measured poles and re-test the V290 sign there.
Agent advphys, 2026-09-09.  Analysis only: builds nothing, flashes nothing, sends nothing.

Part 1  POOLED PSDs, engaged-lateral runs >= 5.12 s, Welch nperseg 512 (0.195 Hz), on the 0x18F wheel rate and the bar,
        for r39 / r3a (V282), r5e_v288 (V288 rev 2), r62_v289 / r63_v289 (V289).
Part 2  CONTROLS: the same pools on DISENGAGED-moving (the loop is off), hands-off / hands-on, v<8 / v>=8, and the 0xE4
        command -- an engaged-only line that is absent from the command is generated by the EPS loop.
Part 3  RE-FIT: search plants (smooth and mode-bearing families; g0, integer-tick tau, f1, fp, zp, kappa) so the EXACT
        closed-loop pole of the V282 image sits at 20.0 Hz AND that of the V289 image at 16.7 Hz -- root-finding on each
        build's own byte-read loop (adv_v290_physics.Blocks / Plant / mode_pole).  Optionally also constrain the V282
        pole's zeta to the wire's free-decay median 0.027.  Then score the V290 candidates and their SIGN CONTROLS.
Part 4  MECHANISM: the added term's own phase vs frequency, and the damping axis at 16.7 vs 20.3 Hz on a re-fit.

Run:  python adv_v290_relocation.py    (writes _scratch/adv_v290_relocation.txt beside it)
"""
import os
import sys

import numpy as np
from scipy import signal

HERE = os.path.dirname(os.path.abspath(__file__))
KIT = os.path.dirname(os.path.dirname(os.path.dirname(HERE)))
SCR = os.path.join(HERE, "_scratch")
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(KIT, "analysis-2020accord", "studies", "v280"))
sys.path.insert(0, os.path.join(KIT, "analysis-2020accord", "lib"))
os.environ.setdefault("ACCORD_FIRMWARE_ROOT", "C:/Users/dudei/Desktop/Projects/accord-firmwares")
import creep20_loop_id as C20                 # noqa: E402
import adv_v290_physics as A                  # noqa: E402

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

FS = 100.0
ROUTES = (("r39", "V282"), ("r3a", "V282"), ("r5e_v288", "V288r2"), ("r62_v289", "V289"), ("r63_v289", "V289"))
F282_TARGET, F289_TARGET, Z282_TARGET = 20.0, 16.7, 0.027
OUT = []


def pr(s=""):
    print(s, flush=True); OUT.append(s)


def pool(g, msk, keys, nps=512):
    P = {k: 0 for k in keys}; n = 0; secs = 0.0
    for a, b in C20.runs(msk, nps):
        w = b - a
        for k in keys:
            x = g[k][a:b]
            f, p = signal.welch(x - x.mean(), fs=FS, nperseg=nps)
            P[k] = P[k] + w * p
        n += w; secs += w / FS
    if n == 0:
        return None, None, 0.0
    f, _ = signal.welch(np.zeros(nps), fs=FS, nperseg=nps)
    return f, {k: P[k] / n for k in keys}, secs


def bp(f, P, lo, hi):
    return float(np.sum(P[(f >= lo) & (f <= hi)]) * (f[1] - f[0]))


def pk(f, P, lo, hi):
    m = (f >= lo) & (f <= hi); return float(f[m][int(np.argmax(P[m]))])


class D(A.Blocks):
    """(ii-d): sum-node H = N - gd*(1 - z^-1)*(1 - N), injected pre-lag inside the existing 0xC4C00 cave."""

    def __init__(self, cc, gd):
        super().__init__(cc, True, 0.0); self.gd = gd

    def bracket(self):
        hn, hd = self.Hlag; nn, nd = self.N; mn, _ = self.oneMinusN
        return A.pmul(hn, A.padd(nn, -self.gd * np.convolve(np.array([1.0, -1.0]), mn))), A.pmul(hd, nd)


def main():
    c, _ = A.read_v289()
    c282 = dict(c); c282["fb_a"], c282["fb_b"] = 923, 1560
    el282, el289 = A.Blocks(c282, False, 0.0), A.Blocks(c, True, 0.0)

    pr("=" * 130)
    pr("1. POOLED PSDs -- engaged lateral, runs >= 5.12 s, Welch nperseg 512 (0.195 Hz bins)")
    pr("=" * 130)
    G = {}
    for tag, build in ROUTES:
        try:
            G[tag] = C20.load(tag)
        except Exception as e:  # noqa: BLE001
            pr("FAILED %s: %r" % (tag, e)); continue
        g = G[tag]
        f, P, secs = pool(g, g["eng"], ("bar", "wire"))
        pr("  %-9s %-7s %4.0f s | rate: peak 12-30 %5.2f Hz  14-17 %8.4g  18-22 %8.4g  ratio %6.2f | bar 14-17 %8.4g 18-22 %8.4g" % (
            tag, build, secs, pk(f, P["wire"], 12, 30), bp(f, P["wire"], 14, 17), bp(f, P["wire"], 18, 22),
            bp(f, P["wire"], 14, 17) / bp(f, P["wire"], 18, 22), bp(f, P["bar"], 14, 17), bp(f, P["bar"], 18, 22)))

    pr("\n" + "=" * 130)
    pr("2. CONTROLS -- is the 16.5 Hz line ENGAGED-ONLY, and is it in the command?")
    pr("=" * 130)
    for tag, build in ROUTES:
        if tag not in G:
            continue
        g = G[tag]; g["cmdf"] = g["cmd"]
        pr("\n  === %s (%s)" % (tag, build))
        for lab, msk in (("ENGAGED lateral", g["eng"]),
                         ("DISENGAGED, moving", (~g["eng"]) & (g["vego"] > 0.5)),
                         ("ENG hands-off |bar|<400", g["eng"] & (np.abs(g["bar"]) < 400)),
                         ("ENG v<8 m/s", g["eng"] & (g["vego"] < 8)),
                         ("ENG v>=8 m/s", g["eng"] & (g["vego"] >= 8))):
            f, P, secs = pool(g, msk, ("bar", "wire", "cmdf"))
            if f is None or secs < 20:
                pr("    %-24s (only %.0f s)" % (lab, secs)); continue
            pr("    %-24s %4.0f s | rate pk %5.2f Hz  14-17 %8.4g  18-22 %8.4g  ratio %6.2f | cmd 14-17 %7.4g 18-22 %7.4g" % (
                lab, secs, pk(f, P["wire"], 12, 30), bp(f, P["wire"], 14, 17), bp(f, P["wire"], 18, 22),
                bp(f, P["wire"], 14, 17) / bp(f, P["wire"], 18, 22), bp(f, P["cmdf"], 14, 17), bp(f, P["cmdf"], 18, 22)))

    pr("\n" + "=" * 130)
    pr("3. RE-FIT the plant to BOTH measured poles (V282 %.1f Hz, V289 %.1f Hz), then re-test the V290 SIGN" % (F282_TARGET, F289_TARGET))
    pr("=" * 130)
    for with_z in (False, True):
        cands = []
        for fp in np.arange(17.0, 27.1, 0.5):
            for zp in (0.02, 0.04, 0.07, 0.12, 0.2, 0.35, 0.5):
                for kap in (None, 0.3, 0.6, 1.0, 1.5):
                    for tau in (0.002, 0.004, 0.006, 0.008, 0.010):
                        for f1 in (3.0, 5.0, 12.0, 30.0):
                            for g0 in np.exp(np.linspace(np.log(0.008), np.log(0.35), 14)):
                                pl = A.Plant(dict(g0=g0, tau=tau, f1=f1, fp=fp, zp=zp, kappa=kap, label="m"), 1.0,
                                             "fp%.1f zp%.2f k%s tau%.0fms f1%.0f g0%.3f" % (fp, zp, kap, 1e3 * tau, f1, g0))
                                f2, z2 = A.mode_pole(el282, pl, 10, 32)
                                f9, z9 = A.mode_pole(el289, pl, 10, 32)
                                if not (np.isfinite(f2) and np.isfinite(f9)):
                                    continue
                                e = abs(f2 - F282_TARGET) + abs(f9 - F289_TARGET) + (3 * abs(z2 - Z282_TARGET) if with_z else 0.0)
                                cands.append((e, pl, f2, z2, f9, z9))
        cands.sort(key=lambda t: t[0])
        pr("\n  --- constraints: two poles%s ---" % (" + V282 zeta ~ %.3f" % Z282_TARGET if with_z else ""))
        pr("  %-42s %-20s %-20s | %-11s | %-11s | %-11s | %-11s" % (
            "plant", "V282 pole", "V289 pole", "-4dn PROPOSD", "+4dn CONTROL", "-n/8 PROPOSD", "+n/8 CONTROL"))
        seen = set(); shown = 0
        for e, pl, f2, z2, f9, z9 in cands:
            k = (round(f2, 1), round(f9, 1), round(z2, 3), round(z9, 3))
            if k in seen:
                continue
            seen.add(k)
            row = []
            for el in (D(c, 4.0), D(c, -4.0), A.Blocks(c, True, 1 / 8), A.Blocks(c, True, -1 / 8)):
                f0, z0 = A.mode_pole(el, pl, 10, 32)
                row.append("%+6.3f@%4.1f" % (z0, f0))
            pr("  %-42s %5.2f Hz z %+.3f    %5.2f Hz z %+.3f    | %s | %s | %s | %s" % (pl.label[:42], f2, z2, f9, z9, *row))
            shown += 1
            if shown >= 8:
                break

    pr("\n" + "=" * 130)
    pr("4. MECHANISM -- the term was aimed at 20.3 Hz; the pole is now at ~16.5 Hz")
    pr("=" * 130)
    mn, md = el289.oneMinusN
    pr("   f Hz | ang(1-N) | term ang in R (ii-c) | term ang in R (ii-d) | |term| (ii-c) | |term| (ii-d)")
    for f in (14, 15, 16, 16.7, 17, 18, 19, 20.3, 22):
        t_c = A.Blocks(c, True, 1 / 8).Rf(f) - el289.Rf(f)
        t_d = D(c, 4.0).Rf(f) - el289.Rf(f)
        pr("   %4.1f | %+7.1f  | %+7.1f              | %+7.1f              | %6.3f        | %6.3f" % (
            f, np.degrees(np.angle(A.pev(mn, f) / A.pev(md, f))), np.degrees(np.angle(t_c)), np.degrees(np.angle(t_d)), abs(t_c), abs(t_d)))
    pl = A.Plant(dict(g0=0.087, tau=0.002, f1=12.0, fp=22.0, zp=0.12, kappa=0.3, label="refit"), 1.0, "refit fp22 zp.12 k.3")
    for f0 in (16.7, 20.3):
        w0 = 2 * np.pi * f0 / A.FS; al = np.sin(w0) / 6.0
        bpn = np.array([al, 0, -al]) / (1 + al)
        bpd = np.array([1.0, -2 * np.cos(w0) / (1 + al), (1 - al) / (1 + al)])

        class Ideal(A.Blocks):
            def __init__(self, cc, k, phi):
                super().__init__(cc, True, 0.0); self.k, self.phi = k, phi

            def R(self):
                n, dd = super().R()
                term = self.k * np.exp(1j * np.radians(self.phi)) * bpn
                return A.padd(A.pmul(n, bpd), A.pmul(term, dd)), A.pmul(dd, bpd)

        zs = []
        for phi in range(0, 360, 15):
            e = Ideal(c, 0.3, phi)
            n, dd = A.loop(e, pl); ch = A.padd(dd, n)
            wr = np.roots(ch[::-1]); wr = wr[np.abs(wr) > 1e-12]
            z = 1 / wr; s = np.log(z) * A.FS
            fq = s.imag / (2 * np.pi); ze = -s.real / np.abs(s)
            m = (fq >= 10) & (fq <= 32)
            zs.append(np.min(ze[m]) if m.any() else np.nan)
        ph = np.arange(0, 360, 15); k = int(np.nanargmax(zs))
        pr("   damping axis for a BP at %.1f Hz on the re-fit: theta = %3d deg (zeta %.3f); worst at %3d deg (%.3f)" % (
            f0, ph[k], zs[k], ph[int(np.nanargmin(zs))], np.nanmin(zs)))
    with open(os.path.join(SCR, "adv_v290_relocation.txt"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(OUT) + "\n")
    pr("\nwrote _scratch/adv_v290_relocation.txt")


if __name__ == "__main__":
    main()
