# -*- coding: utf-8 -*-
"""studies/grind/r24_lane.py -- THE r24 LANE'S ARM OF THE RETURN RATIO, ready to import.

    R_r24(f) = -kappa * (0xC6446/1024) * D4(f) * B(f)      D4(f) = 0.5*(1 - exp(-j 2 pi f 0.004))
    L_r24(f) = R_r24(f) * CPD * G(f)                       CPD = 8; G = THE SAME PLANT the servo sees
    L_tot(f) = L_servo(f) + L_r24(f)                       char. eq. 1 + L_tot = 0

UNITS AND SIGN: aggregator counts per raw count of x = gp-0x6a56 = -(0x18F wire rate).  IDENTICAL to
adv_v290_physics.Blocks.Rf() and loopshape20_loop_model.Elec.ret(), so the two arms ADD DIRECTLY -- both
lanes enter the SAME aggregator FUN_0003aa2c -> gp-0x6b94 with UNIT WEIGHT and reach the motor 1:1
(gp-0x6b94 -> governor FUN_0004503c -> gp-0x6ace -> gp-0x6acc -> gp-0x6b08 -> gp-0x6b98, byte-verified).
The LKAS lane's aggregator term is **gp-0x6b4c**, read at 0x3aa3e (agent `ghidrafill`, 2026-09-13,
TRACE-2026-09-13-lkas-lane-to-aggregator-and-ghidra-gap.md -- it SUPERSEDES the earlier "gp-0x6ad4"
reading and the "gp-0x6b38 is a dead copy" reading; 0x2B41C is a dead TWIN, the live forward is 0x2a2ea).
*** servo() IS A LOWER BOUND ***: the LKAS lane ALSO reaches the aggregator indirectly, gp-0x6b4c ->
FUN_00038148 -> gp-0x6b70 -> gp-0x6ad6 -> gp-0x6ad4, a second summand not modelled here.  Every r24
SHARE computed against servo() is therefore an UPPER bound on r24.

*** DO NOT READ "positive real part" AS "damping". ***  The record labels Re > 0 as damping.  On the pole
computed over a plant family REFITTED WITH r24 IN THE LOOP, r24 at 5244 comes out DE-DAMPING the 20 Hz
mode.  Use the pole, not the sign of Re.  See TRACE-2026-09-13-r24-lane-transfer.md.

*** kappa IS NOT 1.  THREE INDEPENDENT LINES BOUND THE r24 ARM BELOW THE CLOSED FORM: ***
  (1) the cave's own bit-6 comparator (|r24| >= |T|, evaluated INSIDE the ECU at full precision) inverts
      to an effective 0xC6446 of 2268-2747 over 8 strata x 2 routes  =>  kappa ~ 0.45;
  (2) V289 relocated the mode 20.1 -> 16.5 Hz with a notch sitting ONLY in the servo arm, measured on the
      car -- impossible at kappa 1.00 (0 of 5278 plants reproduce both poles), best at kappa 0.10-0.20;
  (3) V281 rev 3 extinguished the 7 Hz cycle at Kp 248, which the kappa 1.00 budget says should have
      survived.
  The record's normalised 7.3 Hz split (LS73/LR73) is the ONE line pointing the other way (kappa ~ 1.45).
  DEFAULT kappa = 0.45; carry [0.10, 1.00] as the working bracket.  PHASE is unaffected and is confirmed
  on the wire by the cave's own bit-4 sign channel to -14..+8 deg.

B(f) measured on V282 routes r39 + r6c (b_of_f_v282.py / B-OF-F-V282-2026-09-13.md, 4016 s engaged).
Generated by _scratch/gen_r24_lane.py from r24_lane_transfer.py's run; regenerate, do not hand-edit.
r24lane, 2026-09-13.  ANALYSIS ONLY.
"""
import numpy as np

TS, FS, CPD = 1e-3, 1000.0, 8.0
GAIN_FLOWN = 5244.0            # 0xC6446, the engaged arm on every build since V67
GAIN_HONDA = 2048.0            # 0xC6440, Honda's own fixed arm (the "lp == 0" rung)
GAIN_MASK = 1024.0             # 0xC6442, the gp-0x671d first-strike latch arm -- NOT live on r39/r6c
KAPPA_DEFAULT = 0.45
KAPPA_BRACKET = (0.10, 1.00)
DEADBAND = 3.0                 # 0xC61F6, applied to s AFTER the gain, in lane-output counts
PRECLAMP, POSTCLAMP = 5120.0, 8192.0
COH_MIN = 0.40

FREQS = [3.0, 3.9, 5.0, 6.0, 7.3, 8.0, 10.0, 12.0, 14.0, 16.0, 18.0, 20.3, 22.0, 25.0, 30.0]

# stratum -> rows of [f, |R_r24|, ang_deg, Re, Im, coherence]  at kappa = 1.0 (closed form at 5244)
R24 = {
 'creep_1_3med': [
   [3.0, 0.5679, 145.12, -0.4658, 0.3247, 0.2927],
   [3.9, 0.7381, 144.47, -0.6007, 0.4289, 0.4225],
   [5.0, 1.3480, 157.92, -1.2491, 0.5067, 0.5653],
   [6.0, 3.0084, 165.90, -2.9177, 0.7329, 0.6941],
   [7.3, 5.0974, 170.72, -5.0308, 0.8217, 0.8810],
   [8.0, 6.1407, 169.71, -6.0419, 1.0969, 0.8410],
   [10.0, 7.8997, 121.60, -4.1393, 6.7284, 0.4139],
   [12.0, 8.7407, 90.84, -0.1281, 8.7398, 0.4532],
   [14.0, 5.6645, 49.14, 3.7058, 4.2841, 0.4431],
   [16.0, 4.2122, 29.23, 3.6759, 2.0569, 0.6666],
   [18.0, 3.6603, 17.15, 3.4976, 1.0793, 0.8507],
   [20.3, 3.6616, 15.48, 3.5287, 0.9775, 0.9314],
   [22.0, 3.3188, 10.51, 3.2631, 0.6054, 0.8227],
   [25.0, 3.3831, 0.34, 3.3830, 0.0201, 0.5255],
   [30.0, 4.0302, -3.26, 4.0237, -0.2292, 0.2381],
  ],
 'creep_1_3': [
   [3.0, 0.8235, 129.87, -0.5279, 0.6321, 0.2427],
   [3.9, 1.0704, 129.22, -0.6768, 0.8292, 0.3304],
   [5.0, 1.3720, 128.43, -0.8527, 1.0747, 0.4122],
   [6.0, 2.7251, 146.27, -2.2664, 1.5132, 0.4618],
   [7.3, 4.6050, 151.69, -4.0543, 2.1836, 0.6326],
   [8.0, 5.5754, 145.75, -4.6085, 3.1378, 0.6181],
   [10.0, 5.3068, 112.28, -2.0122, 4.9105, 0.2891],
   [12.0, 4.8480, 78.82, 0.9404, 4.7559, 0.2506],
   [14.0, 4.3050, 45.35, 3.0256, 3.0625, 0.2404],
   [16.0, 3.7440, 11.88, 3.6638, 0.7708, 0.7434],
   [18.0, 3.3348, 7.44, 3.3067, 0.4318, 0.8497],
   [20.3, 3.5149, 5.55, 3.4984, 0.3402, 0.9045],
   [22.0, 3.2109, 5.09, 3.1983, 0.2849, 0.8235],
   [25.0, 3.1669, -5.95, 3.1498, -0.3283, 0.4245],
   [30.0, 3.7727, -9.55, 3.7204, -0.6259, 0.1661],
  ],
 'loaded_idx68med': [
   [3.0, 0.6631, 176.33, -0.6618, 0.0424, 0.0527],
   [3.9, 0.8619, 175.68, -0.8595, 0.0649, 0.3466],
   [5.0, 1.1048, 174.89, -1.1004, 0.0984, 0.6179],
   [6.0, 2.2697, 176.74, -2.2660, 0.1291, 0.6924],
   [7.3, 4.4522, 173.71, -4.4254, 0.4875, 0.9064],
   [8.0, 5.5264, 173.24, -5.4880, 0.6505, 0.8938],
   [10.0, 5.9835, 121.30, -3.1086, 5.1127, 0.2786],
   [12.0, 6.2180, 69.36, 2.1918, 5.8189, 0.4974],
   [14.0, 4.5152, 32.83, 3.7941, 2.4479, 0.6769],
   [16.0, 3.8710, 24.58, 3.5203, 1.6102, 0.7921],
   [18.0, 3.4060, 17.56, 3.2473, 1.0276, 0.9384],
   [20.3, 3.5394, 13.71, 3.4385, 0.8391, 0.9574],
   [22.0, 3.1814, 13.35, 3.0955, 0.7346, 0.8473],
   [25.0, 3.0447, 4.18, 3.0366, 0.2219, 0.5474],
   [30.0, 3.6271, 0.58, 3.6269, 0.0367, 0.2526],
  ],
 'loaded_any': [
   [3.0, 0.7117, 169.24, -0.6992, 0.1329, 0.0745],
   [3.9, 0.9251, 168.59, -0.9068, 0.1830, 0.3536],
   [5.0, 1.1857, 167.80, -1.1589, 0.2506, 0.6232],
   [6.0, 2.2670, 172.67, -2.2485, 0.2892, 0.6785],
   [7.3, 4.3806, 172.28, -4.3410, 0.5882, 0.8910],
   [8.0, 5.4414, 171.19, -5.3772, 0.8334, 0.8720],
   [10.0, 5.9996, 118.54, -2.8669, 5.2703, 0.3070],
   [12.0, 6.3492, 65.90, 2.5926, 5.7958, 0.4314],
   [14.0, 4.9329, 34.90, 4.0458, 2.8224, 0.6490],
   [16.0, 3.9759, 24.26, 3.6248, 1.6336, 0.7696],
   [18.0, 3.4188, 18.20, 3.2477, 1.0678, 0.9116],
   [20.3, 3.7057, 12.52, 3.6175, 0.8036, 0.9568],
   [22.0, 3.2060, 13.80, 3.1135, 0.7647, 0.8192],
   [25.0, 3.0829, 1.16, 3.0822, 0.0624, 0.4974],
   [30.0, 3.6726, -2.44, 3.6692, -0.1564, 0.1920],
  ],
 'all_eng': [
   [3.0, 0.8518, 170.55, -0.8402, 0.1399, 0.0526],
   [3.9, 1.1071, 169.90, -1.0900, 0.1941, 0.2246],
   [5.0, 1.4190, 169.11, -1.3935, 0.2681, 0.4340],
   [6.0, 2.7235, 171.31, -2.6922, 0.4115, 0.5589],
   [7.3, 5.1477, 170.24, -5.0732, 0.8723, 0.8497],
   [8.0, 6.1463, 166.53, -5.9772, 1.4317, 0.8344],
   [10.0, 8.5441, 127.56, -5.2084, 6.7730, 0.5835],
   [12.0, 9.9647, 113.25, -3.9335, 9.1555, 0.5297],
   [14.0, 9.9068, 100.54, -1.8122, 9.7397, 0.4999],
   [16.0, 6.2541, 66.72, 2.4718, 5.7449, 0.3512],
   [18.0, 3.8856, 32.90, 3.2625, 2.1106, 0.5184],
   [20.3, 3.7974, 8.97, 3.7509, 0.5923, 0.7912],
   [22.0, 4.1076, 7.75, 4.0701, 0.5539, 0.2357],
   [25.0, 4.6503, 5.59, 4.6282, 0.4530, 0.0312],
   [30.0, 5.5398, 1.99, 5.5365, 0.1924, 0.2187],
  ],
 'highway': [
   [3.0, 2.2494, 151.05, -1.9683, 1.0888, 0.0311],
   [3.9, 2.9237, 150.40, -2.5422, 1.4441, 0.0692],
   [5.0, 3.7474, 149.61, -3.2325, 1.8958, 0.1096],
   [6.0, 4.4956, 148.89, -3.8490, 2.3228, 0.2208],
   [7.3, 5.4672, 147.95, -4.6341, 2.9009, 0.7419],
   [8.0, 6.5168, 145.16, -5.3487, 3.7230, 0.8230],
   [10.0, 8.6144, 133.92, -5.9754, 6.2051, 0.7870],
   [12.0, 11.1414, 123.08, -6.0811, 9.3355, 0.6672],
   [14.0, 11.5499, 110.24, -3.9957, 10.8367, 0.6486],
   [16.0, 8.8630, 93.17, -0.4901, 8.8494, 0.4218],
   [18.0, 9.9530, 91.73, -0.3005, 9.9485, 0.3178],
   [20.3, 11.1987, 90.07, -0.0145, 11.1987, 0.3861],
   [22.0, 12.1134, 88.85, 0.2431, 12.1110, 0.0632],
   [25.0, 13.7140, 86.69, 0.7918, 13.6911, 0.2770],
   [30.0, 16.3371, 83.09, 1.9655, 16.2185, 0.3812],
  ],
}

# the LKAS servo arm on V282 (Kp 248 flat, Kd 128), same units: [f, |R_servo|, ang_deg]
SERVO = [
  [3.0, 4.2616, -24.83],
  [3.9, 4.0036, -30.43],
  [5.0, 3.6997, -36.12],
  [6.0, 3.4494, -40.43],
  [7.3, 3.1662, -45.14],
  [8.0, 3.0321, -47.36],
  [10.0, 2.7069, -52.89],
  [12.0, 2.4470, -57.60],
  [14.0, 2.2328, -61.77],
  [16.0, 2.0518, -65.54],
  [18.0, 1.8962, -68.99],
  [20.3, 1.7418, -72.62],
  [22.0, 1.6415, -75.12],
  [25.0, 1.4876, -79.18],
  [30.0, 1.2817, -85.18],
]

# B(f) as a CAUSAL DISCRETE RATIONAL in w = z^-1, zeros imposed at DC and at Nyquist
BFIT = {
 'creep_1_3med': dict(num=[-0.1180480859, 0.1272485271, 0.1180480859, -0.1272485271], den=[1.0, -2.9914923057, 2.9860744156, -0.9946599665], rms_ln_mag=0.1066, rms_phase_deg=14.07, stable=False),
 'creep_1_3': dict(num=[-0.119575533, 0.1242042967, 0.119575533, -0.1242042967], den=[1.0, -2.9789116254, 2.9608124495, -0.9819300921], rms_ln_mag=0.0846, rms_phase_deg=13.62, stable=False),
 'loaded_idx68med': dict(num=[-0.1031443286, 0.11008512, 0.1031443286, -0.11008512], den=[1.0, -2.9877616735, 2.9788189662, -0.9911135946], rms_ln_mag=0.1090, rms_phase_deg=8.96, stable=False),
 'loaded_any': dict(num=[-0.1090209269, 0.1158845389, 0.1090209269, -0.1158845389], den=[1.0, -2.9877696415, 2.9788350686, -0.9911242173], rms_ln_mag=0.1005, rms_phase_deg=9.05, stable=False),
 'all_eng': dict(num=[-0.1060047349, 0.1265840382, 0.1060047349, -0.1265840382], den=[1.0, -2.9933105799, 2.9892200766, -0.9960861939], rms_ln_mag=0.1349, rms_phase_deg=12.67, stable=False),
 'highway': dict(num=[-0.0797868641, 0.1626988314, 0.0797868641, -0.1626988314], den=[1.0, -2.9846826726, 2.9656550408, -0.9815357811], rms_ln_mag=0.0342, rms_phase_deg=1.25, stable=False),
}


def D4(f):
    """the lane's lag-4 backward difference at 1 kHz, exactly as the firmware computes it."""
    return 0.5 * (1.0 - np.exp(-2j * np.pi * np.asarray(f, float) * 0.004))


def _rows(stratum):
    return np.asarray(R24[stratum], float)


def coherence(f, stratum="creep_1_3med"):
    r = _rows(stratum)
    return np.interp(np.asarray(f, float), r[:, 0], r[:, 5])


def is_usable(f, stratum="creep_1_3med"):
    """False where B was NOT identified.  10-14 Hz fails in EVERY stratum -- that band is a fit."""
    return coherence(f, stratum) >= COH_MIN


def R_r24(f, kappa=KAPPA_DEFAULT, gain=GAIN_FLOWN, stratum="creep_1_3med"):
    """aggregator counts per raw count of x, from the MEASUREMENT (log-magnitude / unwrapped-phase
    interpolation over the coherence-usable points).  Add directly to adv_v290_physics.Blocks.Rf(f)."""
    r = _rows(stratum)
    ok = r[:, 5] >= COH_MIN
    fu, mu, pu = r[ok, 0], r[ok, 1], np.unwrap(np.radians(r[ok, 2]))
    f = np.asarray(f, float)
    m = np.exp(np.interp(f, fu, np.log(mu))) * np.exp(1j * np.interp(f, fu, pu))
    return m * kappa * (gain / GAIN_FLOWN)


def R_r24_poly(kappa=KAPPA_DEFAULT, gain=GAIN_FLOWN, stratum="creep_1_3med", extra=None):
    """(num, den) in w = z^-1, for a characteristic polynomial (adv_v290_physics.poles style).
    extra = an optional (num, den) filter a cave would add on r24."""
    fb = BFIT[stratum]
    num = np.convolve(np.array([0.5, 0.0, 0.0, 0.0, -0.5]), np.asarray(fb["num"], float))
    num = num * (-kappa * gain / 1024.0)
    den = np.asarray(fb["den"], float)
    if extra is not None:
        num, den = np.convolve(num, extra[0]), np.convolve(den, extra[1])
    return num, den


def servo(f):
    """the V282 LKAS servo arm (Kp 248 flat, Kd 128), same units -- for ratios and sanity checks."""
    s = np.asarray(SERVO, float)
    return (np.exp(np.interp(f, s[:, 0], np.log(s[:, 1])))
            * np.exp(1j * np.interp(f, s[:, 0], np.unwrap(np.radians(s[:, 2])))))


LS73 = 0.55 * np.exp(1j * np.radians(96.0))     # LOOPSHAPE-LAGPOLE-KD Sec.4, NORMALISED split, Ls + Lr == 1
LR73 = 1.19 * np.exp(1j * np.radians(-27.0))


def gate73(Rs_ratio=1.0, Rr_ratio=1.0):
    """The 7.3 Hz strong-turn gate, GENERALISED so the r24 arm can move too.  Rs_ratio / Rr_ratio are each
    the new arm over today's arm AT 7.3 Hz.  SCALE-FREE: it never needs |r24| in absolute counts, which is
    why it stays usable despite the kappa dispute.  Today = 1.0028; the record's gate is <= 1.000."""
    return float(abs(LS73 * Rs_ratio + LR73 * Rr_ratio))


def hp_cave(f0):
    """one-pole high-pass a cave could add on r24: y = x - lp(x), lp = (1-a)/(1 - a w), a = exp(-2 pi f0/FS)."""
    a = float(np.exp(-2 * np.pi * f0 / FS))
    return np.array([a, -a]), np.array([1.0, -a])


def bp_cave(f0, fhi):
    """hp(f0) * lp(fhi), as (num, den) in w."""
    hn, hd = hp_cave(f0)
    a2 = float(np.exp(-2 * np.pi * fhi / FS))
    return np.convolve(hn, np.array([1 - a2])), np.convolve(hd, np.array([1.0, -a2]))

