# -*- coding: utf-8 -*-
r"""op_report.py -- writes judge-operability/op_probe_out.txt from the JSON caches of op_probe.py, op_signed_arb.py and
op_merge_probe.py (in _scratch/angle_loop/judge-operability/).  ANALYSIS ONLY.  usage: python op_report.py"""
from __future__ import annotations

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
KIT = HERE.parents[4]
J = KIT / "_scratch" / "angle_loop" / "judge-operability"
BANDS = (("<8", 0, 7.99), (">=8", 8, 99), ("8-10", 8, 10), ("10-12.5", 10.01, 12.5), ("12.5-15", 12.51, 15),
         ("15-22", 15.01, 22), (">22", 22.01, 99))


def table(R, scn, key, cands, agg=max, title=""):
    L = [f"\n## {scn}.{key} {title}", "| cand | " + " | ".join(b[0] for b in BANDS) + " |",
         "|---|" + "---|" * len(BANDS)]
    for c in cands:
        cells = []
        for nm, lo, hi in BANDS:
            v = [r[key] for r in R[scn] if r["cid"] == c and lo <= r["v"] <= hi]
            cells.append(f"{agg(v):.2f}" if v else "-")
        L.append(f"| {c} | " + " | ".join(cells) + " |")
    return L


def main():
    out = ["# op_probe_out.txt -- JUDGE OPERABILITY probe tables (frame vgr; worst over the members run: nominal and "
           "b_lo*J_hi for the override/crown rows, nominal for cam30). Generated by op_report.py."]
    for tag in ("op_probe", "op_signed_arb", "op_merge_probe"):
        p = J / f"{tag}.json"
        if not p.exists():
            out.append(f"\n# {tag}: cache missing ({p})")
            continue
        R = json.loads(p.read_text())
        cands = []
        for rows in R.values():
            for r in rows:
                if r["cid"] not in cands:
                    cands.append(r["cid"])
        out.append(f"\n# ================= {tag} =================")
        for scn in R:
            keys = [k for k in R[scn][0] if k not in ("cid", "member", "v")]
            for k in keys:
                if k in ("th_rel", "T_end", "Tpk"):
                    continue
                out += table(R, scn, k, cands)
    (HERE / "op_probe_out.txt").write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"wrote {HERE / 'op_probe_out.txt'}")


if __name__ == "__main__":
    main()
