"""IS "GRIND #3" (42-47 Hz) THE SECOND HARMONIC OF THE 21-26 Hz MODE?

HYPOTHESIS (orchestrator, BELIEF): there is ONE mode at ~21-26 Hz and the 42-47 Hz feature is
its SECOND HARMONIC, generated by a nonlinearity in the loop -- so "grind #3 producing a lower
ratcheting-like mode" is ONE phenomenon, not two.
Prior in the record: `memory/accord/builds/accord-v59-parametric-pump-marginal.md` -- "42.19 Hz = 2x the
21.09 Hz mode".

WHY A PHASE TEST AND NOT A SPECTRAL ONE
  Two independent modes that happen to sit at f and ~2f have INDEPENDENT phases.  A true
  harmonic born of a nonlinearity is PHASE-LOCKED: the biphase
        phi = arg(X(f)^2 . conj(X(2f)))
  is the same in every window.  ⭐ phi is INVARIANT to any timing offset tau (a delay rotates
  arg X(f) by -2.pi.f.tau and arg X(2f) by -4.pi.f.tau, which cancels exactly) -- which is why
  it survives this corpus's 11 % CAN arrival jitter.

🛑 INSTRUMENT LIMITS, MEASURED FIRST, NOT ASSUMED
  0x18F (the source of `tq` and `rate_f`) arrives at 100.88 Hz => NYQUIST 50.44 Hz.
  0x1AB (427) arrives at 49.76 Hz => Nyquist 24.9 Hz, i.e. 427 IS BLIND AT 42 Hz.  Not used.
  0x14A (the grid, and the source of `rate_c`) arrives at 101.15 Hz -- `rate_c` is NATIVE on the
  analysis grid with NO held-last resampling, so it is carried as an independent channel.
  => the fundamental band is capped at 25.2 Hz so that 2f stays BELOW 50.44 Hz and the harmonic
     is never itself an alias.  Band: f in [20.0, 25.0], 2f in [40.0, 50.0].
  ⚠ Content genuinely above 50.44 Hz folds INTO 40-50 Hz (e.g. 55 Hz -> 45.9 Hz).  This channel
    cannot exclude that.  It is stated, not waved away -- but note an aliased INDEPENDENT mode
    would NOT be phase-locked to the fundamental, so the phase test is partly robust to it.

CONTROLS, ALL RUN BEFORE THE MEASUREMENT IS QUOTED
  N1  CROSS-WINDOW SHUFFLE -- pair X(2f) from window j != i with X(f) from window i.  Destroys
      the within-window phase relation, preserves both marginals.  THE null.
  N2  NON-HARMONIC BAND PAIR -- same fundamental, partner band at 1.65x instead of 2x.  If the
      statistic is as large there, it is not a harmonic relation.
  N3  MANUAL ARM -- an instrument-generated harmonic (quantisation, sample-and-hold) must appear
      in manual too.  A loop nonlinearity must not.
  N4  INDEPENDENT CHANNEL -- `rate_c`, which never passes through the held-last resampler.
  Episode bootstrap throughout, never window.
"""
# --- PATH BOOTSTRAP (repo reorg 2026-08-26) -------------------------------
# This file imports sibling modules by bare name.  It used to sit flat in the
# kit directory; now that it is nested, put the kit root and every code
# subfolder on sys.path so those imports still resolve from anywhere.
import os as _os, sys as _sys
_r = _os.path.dirname(_os.path.abspath(__file__))
while not _os.path.isfile(_os.path.join(_r, ".pkgroot")):
    _n = _os.path.dirname(_r)
    if _n == _r:
        raise RuntimeError("no .pkgroot marker above " + __file__)
    _r = _n
_p = [_r]
for _b, _ds, _fs in _os.walk(_r):
    _ds[:] = [_x for _x in _ds if not _x.startswith((".", "_")) and _x not in
              ("rlogs", "ghidra_project", "__pycache__", "reference/opendbc")]
    _p.extend(_os.path.join(_b, _x) for _x in _ds)
_sys.path[:0] = [_x for _x in _p if _x not in _sys.path]
del _os, _sys, _r, _p, _b, _ds, _fs
# --- end path bootstrap ---------------------------------------------------
import os
import sys
import numpy as np

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))))
import _gate2_boost_lib as L                                       # noqa: E402

try:
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')
except Exception:
    pass

KPH = 3.6
NPER = int(round(4 * L.FS))                 # 4 s, the kit's frozen estimator
f = np.fft.rfftfreq(NPER, 1 / L.FS)
WIN = np.hanning(NPER + 1)[:NPER]
F_LO, F_HI = 20.0, 25.0                     # fundamental; 2f stays < 50.44 Hz Nyquist
C_LO, C_HI = 20.0, 25.0                     # N2 control fundamental (same)
C_MULT = 1.65                               # N2 control partner multiplier (NOT 2)


def windows(tag, sig, mask, nper=NPER):
    """Per-episode list of per-window complex spectra.  Detrended, Hann."""
    d = L.load(tag)
    x = d[sig].astype(float)
    idx = np.flatnonzero(np.diff(mask.astype(np.int8)) != 0) + 1
    b = np.concatenate(([0], idx, [len(mask)]))
    tt = np.arange(nper)
    A = np.vstack([tt, np.ones(nper)]).T
    eps = []
    for i in range(len(b) - 1):
        a0, b0 = b[i], b[i + 1]
        if not mask[a0] or (b0 - a0) < nper:
            continue
        Xs = []
        for s in range(a0, b0 - nper + 1, nper // 2):
            xs = x[s:s + nper]
            if not np.all(np.isfinite(xs)):
                continue
            xs = xs - A @ np.linalg.lstsq(A, xs, rcond=None)[0]
            Xs.append(np.fft.rfft(xs * WIN))
        if Xs:
            eps.append(np.array(Xs))
    return eps


def biphase_stats(X, lo=F_LO, hi=F_HI, mult=2.0):
    """Bicoherence b^2 and unweighted resultant R over the band, for a stack of window spectra.

    b^2(f) = |sum_w X(f)^2 conj(X(mf))|^2 / (sum_w |X(f)|^4 . sum_w |X(mf)|^2)
    R      = |mean_w exp(i.arg(X(f)^2 conj(X(mf))))|      -- amplitude-free
    Both are pooled over the fundamental bins by summing numerator and denominator.
    """
    if len(X) == 0:
        return np.nan, np.nan, 0
    sel = np.flatnonzero((f >= lo) & (f < hi))
    num = 0.0 + 0j
    d1 = 0.0
    d2 = 0.0
    phs = []
    for i in sel:
        j = int(np.argmin(np.abs(f - mult * f[i])))
        tri = X[:, i] ** 2 * np.conj(X[:, j])
        num += tri.sum()
        d1 += (np.abs(X[:, i]) ** 4).sum()
        d2 += (np.abs(X[:, j]) ** 2).sum()
        phs.append(tri / (np.abs(tri) + 1e-30))
    b2 = float(np.abs(num) ** 2 / (d1 * d2)) if d1 * d2 > 0 else np.nan
    R = float(np.abs(np.concatenate(phs).mean()))
    return b2, R, len(sel) * X.shape[0]


def pooled(eps):
    return np.concatenate(eps, axis=0) if eps else np.zeros((0, len(f)), complex)


def run(tag, sig, mask, label, mult=2.0, lo=F_LO, hi=F_HI, nboot=2000, seed=5):
    eps = windows(tag, sig, mask)
    X = pooled(eps)
    if X.shape[0] < 8:
        print("%-34s %-8s  (only %d windows -- skipped)" % (label, sig, X.shape[0]))
        return None
    b2, R, n = biphase_stats(X, lo, hi, mult)
    rng = np.random.default_rng(seed)
    # ---- N1: cross-window shuffle of the harmonic bin (destroys coupling, keeps marginals)
    nb2, nR = [], []
    for _ in range(400):
        perm = rng.permutation(X.shape[0])
        Xs = X.copy()
        sel = np.flatnonzero((f >= lo) & (f < hi))
        for i in sel:
            j = int(np.argmin(np.abs(f - mult * f[i])))
            Xs[:, j] = X[perm, j]
        a, b, _ = biphase_stats(Xs, lo, hi, mult)
        nb2.append(a)
        nR.append(b)
    nb2, nR = np.array(nb2), np.array(nR)
    # ---- episode bootstrap of the statistic
    bb = []
    for _ in range(nboot):
        pick = rng.integers(0, len(eps), len(eps))
        Xb = np.concatenate([eps[j] for j in pick], axis=0)
        bb.append(biphase_stats(Xb, lo, hi, mult)[1])
    bb = np.array(bb)
    print("%-34s %-8s nw=%4d  b2=%.4f  R=%.4f [%.3f,%.3f]   NULL b2 %.4f p95 %.4f | R %.4f "
          "p95 %.4f   p=%.4f"
          % (label, sig, X.shape[0], b2, R, np.percentile(bb, 2.5), np.percentile(bb, 97.5),
             np.median(nb2), np.percentile(nb2, 95), np.median(nR), np.percentile(nR, 95),
             (nR >= R).mean()))
    return dict(b2=b2, R=R, nR=nR, nb2=nb2, boot=bb, nw=X.shape[0])


print("=" * 118)
print("0. INSTRUMENT -- measured, not assumed")
print("=" * 118)
for tag in ('r9e', 'r97'):
    d = L.load(tag)
    t18 = np.asarray(d['raw18_t'], float)
    dt = np.diff(t18)
    dt = dt[(dt > 0) & (dt < 1)]
    print("  %s: 0x18F native %.2f Hz (Nyquist %.2f Hz), arrival jitter p5/p95 %.2f/%.2f ms; "
          "0x1AB %.2f Hz (Nyquist %.2f -- BLIND at 42 Hz)"
          % (tag, 1 / np.median(dt), 0.5 / np.median(dt), 1000 * np.percentile(dt, 5),
             1000 * np.percentile(dt, 95),
             1 / np.median(np.diff(np.asarray(d['raw1ab_t'], float))),
             0.5 / np.median(np.diff(np.asarray(d['raw1ab_t'], float)))))
print("  fundamental band %.1f-%.1f Hz  =>  harmonic %.1f-%.1f Hz, entirely below Nyquist."
      % (F_LO, F_HI, 2 * F_LO, 2 * F_HI))
print("  ⚠ true content above ~50.4 Hz folds into 40-50 Hz and cannot be excluded on this channel.")

print()
print("=" * 118)
print("1. THE TEST -- 2:1 BIPHASE, with its own null beside every number")
print("=" * 118)
print("  b2 = bicoherence (amplitude-weighted).  R = unweighted phase resultant (0 = uniform,")
print("  1 = perfectly locked).  NULL = 400 cross-window shuffles of the harmonic bin.")
print("  p = fraction of shuffles reaching R.  Bracket on R = 2000-draw EPISODE bootstrap.")
print()
RES = {}
for tag, nm in (('r9e', 'V103 6x'), ('r97', 'STOCK 1x'), ('r96', 'V102 6x')):
    d = L.load(tag)
    eng = d['cc_lat'] > 0.5
    v = d['v_rear'].astype(float) * KPH
    for arm, m in (('ENGAGED', eng), ('ENGAGED >=60 km/h', eng & (v >= 60)),
                   ('MANUAL  (N3 control)', ~eng)):
        RES[(tag, arm, 'rate_f')] = run(tag, 'rate_f', m, "%s  %s" % (nm, arm))
    RES[(tag, 'ENGAGED', 'rate_c')] = run(tag, 'rate_c', eng, "%s  ENGAGED (N4 channel)" % nm)

print()
print("=" * 118)
print("2. N2 -- THE NON-HARMONIC CONTROL PAIR (partner at %.2fx, not 2x)" % C_MULT)
print("=" * 118)
for tag, nm in (('r9e', 'V103 6x'), ('r97', 'STOCK 1x'), ('r96', 'V102 6x')):
    d = L.load(tag)
    eng = d['cc_lat'] > 0.5
    run(tag, 'rate_f', eng, "%s  ENGAGED  x%.2f" % (nm, C_MULT), mult=C_MULT, lo=C_LO, hi=C_HI)

print()
print("=" * 118)
print("3. BAND ENERGY -- is there anything AT 40-50 Hz to be a harmonic OF?")
print("=" * 118)
BB = [(15, 20), (20, 25), (25, 30), (30, 40), (40, 50)]
print("%22s %10s" % ('route / arm', 'nw') + "".join("%12s" % ("%g-%g" % b) for b in BB))
for tag, nm in (('r97', 'STOCK 1x'), ('r96', 'V102 6x'), ('r9e', 'V103 6x')):
    d = L.load(tag)
    eng = d['cc_lat'] > 0.5
    v = d['v_rear'].astype(float) * KPH
    for arm, m in (('ENG', eng), ('ENG>=60', eng & (v >= 60)), ('MANUAL', ~eng)):
        X = pooled(windows(tag, 'rate_f', m))
        if X.shape[0] < 4:
            continue
        U = (WIN ** 2).sum()
        S = (np.abs(X) ** 2).mean(0) / (L.FS * U)
        row = [np.sqrt(S[(f >= a) & (f < b)].sum() * (f[1] - f[0])) for a, b in BB]
        print("%22s %10d" % ("%s %s" % (nm, arm), X.shape[0])
              + "".join("%12.4f" % r for r in row))
print("  band RMS of rate_f, deg/s.  ⚠ 1.25x low in absolute terms (rate_f = 0.7996x true).")
