#!/usr/bin/env python3
"""IS THE ~7.8 Hz RATCHET A RELAY LIMIT CYCLE, OR A RESONANCE?  And can micro- be separated
from macro-ratcheting?  Route `6e` (V85) primary, `6d` (V84) and `67` (V81) as controls.

MOTIVATION.  `FUN_00038148` computes `resid = estimator_out - modelled_torque` and writes
`gp-0x6b70 = clamp(SIGN(resid) * LERP(|resid|), +-8192)`, which the assist aggregator
`FUN_00037fe6` adds with enable byte `0xC64B0 = 1`.  A RELAY's oscillation frequency is set by the
LOOP, not by road speed -- which is exactly the macro-ratchet's recorded signature (7.79 Hz median,
speed-invariant, present in the bar and the angle rate but NOT in openpilot's command).

🛑 WHAT SEPARATES A RELAY FROM A RESONANCE, and why each test is decisive:

  T1 ODD-HARMONIC COMB.  A relay output is an odd-symmetric square-ish wave, so its spectrum is
     f0, 3f0, 5f0 ... with the EVEN harmonics absent.  A linear resonance driven by broadband road
     input has NO harmonic structure at all.  Measured as prominence over the local floor at
     k*f0, k = 2..5, against a DECOY fundamental (f0 * 1.37) that shares every other property of
     the estimator.  🛑 The decoy is the control that makes this falsifiable: if the comb is an
     artefact of the prominence estimator, the decoy shows it too.

  T2 3:1 PHASE LOCKING.  The comb could be coincidence -- three independent modes.  If the third
     harmonic is GENERATED by the same relay, its phase is locked: 3*phi_1 - phi_3 is constant, not
     uniform.  n:m phase-synchronisation index over time inside each window, with a null built by
     pairing the fundamental of one window against the third harmonic of ANOTHER.  A resonance
     triple cannot produce phase locking; a relay must.

  T3 SPEED-LOCKED vs FIXED LINE.  🛑 Wheel order 2 sits at 2*v/2.0805 Hz and lands INSIDE 6-9 Hz
     for v = 6.2-9.4 m/s.  Route 6e spends 20.7% of engaged windows there against route 6d's 6.7%,
     so the 6-9 Hz band is NOT a clean firmware channel on this route.  This decomposes the band
     into a speed-tracking ridge and a speed-invariant ridge -- which is also the best available
     handle on micro- versus macro-ratcheting.

  T4 SWITCHING-SURFACE TIMING.  A relay chatters AT its switching surface.  So the 6-9 Hz envelope
     should peak at the ZERO CROSSINGS of the low-frequency residual, within a few tens of ms.  A
     resonance's envelope tracks excitation AMPLITUDE and is indifferent to the crossings.
     Zero-crossing-triggered average against a null of randomly placed pseudo-crossings.
     🛑 The trigger band (0.5-4 Hz) and the response band (6-9 Hz) are DISJOINT, so this cannot be
     an autocorrelation artefact.

  T5 THE UPSTREAM FRICTION TERM.  V85's probe reports `|gp-0x6ae2|` (the OTHER Coulomb term, the
     one `0xC40BC` linearised) at two thresholds.  Is the 6-9 Hz content conditional on it?
     ⚠ `gp-0x6ae2` is NOT `gp-0x6b70`; a null here does not exonerate `FUN_00038148`.

  W0 WHEEL-ORDER-CLEAN RE-TEST of the band ratios already computed by `score/score_v85_r6e_bands.py`,
     dropping every window whose order-1..4 line lands inside the band being scored.

🛑 SAMPLING.  ~101.04 Hz.  Nyquist 50.5 Hz, so 3*f0 = 23.4 Hz and 5*f0 = 39 Hz are both resolved;
7*f0 = 54.5 Hz is NOT and is never used.

Usage:
    python studies/misc/relay_fingerprint_r6e.py            # W0 + T1..T5
"""
# --- PATH BOOTSTRAP (repo reorg 2026-08-26) -------------------------------
# This file imports sibling modules by bare name.  It used to sit flat in the
# kit directory; now that it is nested, put the kit root and every code
# subfolder on sys.path so those imports still resolve from anywhere.
import os as _os, sys as _sys
_r = _os.path.dirname(_os.path.abspath(__file__))
while not _os.path.isfile(_os.path.join(_r, ".pkgroot")):
    _n = _os.path.dirname(_r)
    if _n == _r:
        raise RuntimeError("no .pkgroot marker above " + __file__)
    _r = _n
_p = [_r]
for _b, _ds, _fs in _os.walk(_r):
    _ds[:] = [_x for _x in _ds if not _x.startswith((".", "_")) and _x not in
              ("rlogs", "ghidra_project", "__pycache__", "reference/opendbc")]
    _p.extend(_os.path.join(_b, _x) for _x in _ds)
_sys.path[:0] = [_x for _x in _p if _x not in _sys.path]
del _os, _sys, _r, _p, _b, _ds, _fs
# --- end path bootstrap ---------------------------------------------------
import json
import sys
from pathlib import Path

import numpy as np
from scipy.signal import butter, filtfilt, hilbert

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

HERE = Path(__file__).resolve().parents[2]
ROOT = HERE.parent
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(ROOT / "analysis-2020accord"))

import score_v85_r6e_bands as SB  # noqa: E402  -- owns the route table and the loaded records
import _grind2_lib as G  # noqa: E402
import _r31_common as C31  # noqa: E402

CIRC = 2.0805
NW = 1024                       # 10.13 s at 101.04 Hz -> 0.0987 Hz bins.  f0 and 3f0 both clean.
HOPW = 512
ROUTES = [("V85/r6e", "_scratch/cache/r6e", "r6es", list(range(7))),      # seg 7 is parked (0 s engaged)
          ("V84/r6d", "_scratch/cache/r6d", "r6ds", list(range(11))),
          ("V81/r67", "_scratch/cache/r67x", "r67xs", list(range(13)))]
F_LO, F_HI = 6.0, 9.0
MACRO = 7.79                    # the recorded macro-ratchet line, Hz
RNG = np.random.default_rng(85_7790)
OUT = {}


def hdr(s):
    print("\n" + "=" * 108 + f"\n{s}\n" + "=" * 108, flush=True)


def _boot_med(vals, units, nboot=2000):
    """Median with an EPISODE bootstrap CI. `units` is the resampling-unit label per value."""
    vals = np.asarray(vals, float)
    ok = np.isfinite(vals)
    vals, units = vals[ok], np.asarray(units)[ok]
    if len(vals) < 4:
        return np.nan, np.nan, np.nan, len(vals)
    groups = {}
    for v, u in zip(vals, units):
        groups.setdefault(u, []).append(v)
    keys = list(groups)
    draws = np.empty(nboot)
    for k in range(nboot):
        idx = RNG.integers(0, len(keys), len(keys))
        draws[k] = np.median(np.concatenate([groups[keys[i]] for i in idx]))
    return (float(np.median(vals)), float(np.percentile(draws, 2.5)),
            float(np.percentile(draws, 97.5)), len(vals))


# =====================================================================================================
#  WINDOWING -- one pass over the raw per-segment caches, shared by T1..T5
# =====================================================================================================
def windows(route, cache, pfx, segs, engaged=True):
    """Yield dicts with the raw window plus every covariate the tests need."""
    b_lf = butter(2, [0.5, 4.0], btype="band", fs=101.0)
    b_bp = butter(2, [F_LO, F_HI], btype="band", fs=101.0)
    out = []
    for s in segs:
        p = ROOT / cache / f"{pfx}{s}.npz"
        if not p.exists():
            continue
        d = C31.load(s, ROOT / cache, pfx)
        fs = C31.fs_of(d)
        t = np.asarray(d["t"], float)
        tq = np.asarray(d["tq"], float)
        v = np.asarray(d["cs_v"], float)
        lat = np.asarray(d["cc_lat"], float) > 0.5
        rate = np.abs(np.asarray(d["rate_c"], float))
        eff = np.abs(np.asarray(d["cs_tq"], float))
        pr = np.asarray(d["probe"], float).astype(int) if "probe" in d else None
        mask = lat if engaged else ~lat
        for a, b in C31.runs_of(mask, t, NW):
            x_lf = filtfilt(*b_lf, tq[a:b])
            x_bp = filtfilt(*b_bp, tq[a:b])
            env = np.abs(hilbert(x_bp))
            for j0 in range(0, (b - a) - NW + 1, HOPW):
                sl = slice(j0, j0 + NW)
                seg = tq[a:b][sl]
                if not np.all(np.isfinite(seg)):
                    continue
                r = dict(build=route, seg=int(s), t0=float(t[a:b][sl][0]),
                         blk=f"{s}:{a}:{j0 // (HOPW * 2)}", ep=f"{s}:{a}",
                         v=float(np.median(v[a:b][sl])), rate=float(np.median(rate[a:b][sl])),
                         eff=float(np.median(eff[a:b][sl])), fs=float(fs),
                         x=seg, x_lf=x_lf[sl], env=env[sl])
                if pr is not None:
                    q = pr[a:b][sl]
                    for nm, bit in (("b7", 0x80), ("b6", 0x40), ("b5", 0x20), ("b4", 0x10)):
                        r[nm] = float(np.mean((q & bit) != 0))
                out.append(r)
    return out


def spectra(recs):
    """Attach the periodogram, the prominence spectrum and the free 5-12 Hz argmax."""
    for r in recs:
        P = C31.periodogram(r["x"], r["fs"], nfft=NW, detrend=True)
        f = np.fft.rfftfreq(NW, 1.0 / r["fs"])
        R = G.prom_spectrum(f, P, halfwin=3.0, exclude=0.6)
        r["f"], r["P"], r["R"] = f, P, R
        m = (f >= 5.0) & (f <= 12.0) & np.isfinite(R)
        r["f_free"] = float(f[np.argmax(np.where(m, R, -np.inf))]) if m.any() else np.nan
        r["p_free"] = float(np.nanmax(np.where(m, R, np.nan))) if m.any() else np.nan
        mb = (f >= F_LO) & (f <= F_HI) & np.isfinite(R)
        r["f0"] = float(f[np.argmax(np.where(mb, R, -np.inf))]) if mb.any() else np.nan
        r["p0"] = float(np.nanmax(np.where(mb, R, np.nan))) if mb.any() else np.nan
    return recs


def prom_at(r, f_target, half=0.35):
    """Max prominence within +-half Hz of f_target; NaN above 45 Hz or off-grid."""
    if not np.isfinite(f_target) or f_target > 45.0 or f_target < 1.0:
        return np.nan
    m = (np.abs(r["f"] - f_target) <= half) & np.isfinite(r["R"])
    return float(np.nanmax(r["R"][m])) if m.any() else np.nan


# =====================================================================================================
#  W0 -- wheel-order-clean re-test of the band ratios
# =====================================================================================================
def w0():
    hdr("W0  WHEEL-ORDER-CLEAN RE-TEST.  🛑 Route 6e's speed distribution puts wheel ORDER 2\n"
        "    (2v/2.0805 Hz) inside 6-9 Hz on 20.7% of engaged windows, against route 6d's 6.7%\n"
        "    and route 67's 8.7%.  Any 6-9 Hz ratio must survive dropping those windows.")
    G.EPKEY = "blk"
    R = SB.build_records()

    def clean(rs, lo, hi):
        keep = []
        for r in rs:
            v = r["v"]
            if any(lo <= k * v / CIRC <= hi for k in (1, 2, 3, 4)):
                continue
            keep.append(r)
        return keep

    OUT["w0"] = {}
    for bd in ("6-9", "18-22", "32-38"):
        lo, hi = {"6-9": (6.0, 9.0), "18-22": (18.0, 22.0), "32-38": (32.0, 38.0)}[bd]
        print(f"\n---- {bd} Hz ----")
        print(f"{'pair':16s} {'all-windows':>22s} {'order-CLEAN':>22s} {'nA':>5s} {'nB':>5s} "
              f"{'cells':>5s}")
        for A, B in (("V85/r6e", "V84/r6d"), ("V85/r6e", "V81/r67"), ("V84/r6d", "V81/r67")):
            a0, b0 = SB.eng(R[A], A), SB.eng(R[B], B)
            a1, b1 = clean(a0, lo, hi), clean(b0, lo, hi)
            r0 = G.boot_cellwise(a0, b0, "e_" + bd, RNG, nboot=1200, min_ep=2, min_win=4)
            r1 = G.boot_cellwise(a1, b1, "e_" + bd, RNG, nboot=1200, min_ep=2, min_win=4)
            print(f"{A.split('/')[0]+'/'+B.split('/')[0]:16s} "
                  f"{r0[0]:7.3f} [{r0[1]:6.3f},{r0[2]:6.3f}] "
                  f"{r1[0]:7.3f} [{r1[1]:6.3f},{r1[2]:6.3f}] "
                  f"{len(a1):5d} {len(b1):5d} {r1[3]:5d}")
            OUT["w0"].setdefault(bd, {})[f"{A}|{B}"] = dict(
                all=[r0[0], r0[1], r0[2], r0[3]], clean=[r1[0], r1[1], r1[2], r1[3]],
                nA_all=len(a0), nA_clean=len(a1), nB_all=len(b0), nB_clean=len(b1))
        print(f"    dropped by the order filter: " + "  ".join(
            f"{b.split('/')[0]} {len(SB.eng(R[b], b)) - len(clean(SB.eng(R[b], b), lo, hi))}"
            f"/{len(SB.eng(R[b], b))}" for b in ("V85/r6e", "V84/r6d", "V81/r67")))


# =====================================================================================================
#  T1 -- the odd-harmonic comb
# =====================================================================================================
def t1(W):
    hdr("T1  ODD-HARMONIC COMB.  prominence at k*f0 over the local floor, k = 2..5, with a DECOY\n"
        "    fundamental at f0 * 1.37 as the control.  A RELAY gives odd >> even; a resonance\n"
        "    gives no comb at all and the decoy reads the same as the real fundamental.")
    OUT["t1"] = {}
    print(f"{'build':10s} {'arm':8s} {'n':>5s} {'f0 med':>7s} | "
          f"{'h2':>6s} {'h3':>6s} {'h4':>6s} {'h5':>6s} | {'odd/even':>22s} | "
          f"{'DECOY odd/even':>22s}")
    for route, arm, recs in W:
        rs = [r for r in recs if np.isfinite(r["f0"])]
        if len(rs) < 10:
            print(f"{route:10s} {arm:8s} {len(rs):5d}  -- too few --")
            continue
        for r in rs:
            for k in (2, 3, 4, 5):
                r[f"h{k}"] = prom_at(r, k * r["f0"])
                r[f"d{k}"] = prom_at(r, k * r["f0"] * 1.37)
            odd = np.nanmean([r["h3"], r["h5"]])
            even = np.nanmean([r["h2"], r["h4"]])
            r["oe"] = odd / even if (np.isfinite(odd) and np.isfinite(even) and even > 0) else np.nan
            dodd = np.nanmean([r["d3"], r["d5"]])
            deven = np.nanmean([r["d2"], r["d4"]])
            r["oe_decoy"] = (dodd / deven if (np.isfinite(dodd) and np.isfinite(deven)
                                              and deven > 0) else np.nan)
        u = [r["blk"] for r in rs]
        hs = [float(np.nanmedian([r[f"h{k}"] for r in rs])) for k in (2, 3, 4, 5)]
        oe = _boot_med([r["oe"] for r in rs], u)
        de = _boot_med([r["oe_decoy"] for r in rs], u)
        print(f"{route:10s} {arm:8s} {len(rs):5d} {np.median([r['f0'] for r in rs]):7.2f} | "
              + " ".join(f"{h:6.2f}" for h in hs)
              + f" | {oe[0]:6.3f} [{oe[1]:6.3f},{oe[2]:6.3f}] | "
                f"{de[0]:6.3f} [{de[1]:6.3f},{de[2]:6.3f}]")
        OUT["t1"][f"{route}|{arm}"] = dict(n=len(rs), h=hs, oe=list(oe), decoy=list(de),
                                           f0=float(np.median([r["f0"] for r in rs])))
    print("\n  🛑 READ: odd/even ~ 1 AND decoy ~ the same ⇒ NO comb ⇒ no relay signature.")


# =====================================================================================================
#  T2 -- 3:1 phase locking
# =====================================================================================================
def t2(W):
    hdr("T2  3:1 PHASE LOCKING between f0 and 3*f0.  psi(t) = 3*phi_1(t) - phi_3(t); PLV = |<e^i psi>|\n"
        "    over the window.  NULL: the fundamental of window i against the 3rd harmonic of a\n"
        "    DIFFERENT window, which destroys the pairing and nothing else.")
    OUT["t2"] = {}
    print(f"{'build':10s} {'arm':8s} {'n':>5s} | {'PLV(3:1)':>22s} | {'shuffled NULL':>22s} | "
          f"{'z':>6s}")
    for route, arm, recs in W:
        rs = [r for r in recs if np.isfinite(r["f0"]) and 6.2 <= r["f0"] <= 8.8]
        if len(rs) < 10:
            print(f"{route:10s} {arm:8s} {len(rs):5d}  -- too few --")
            continue
        for r in rs:
            f0, fsr = r["f0"], r["fs"]
            b1 = butter(2, [max(f0 - 1.0, 0.5), f0 + 1.0], btype="band", fs=fsr)
            b3 = butter(2, [3 * f0 - 2.0, min(3 * f0 + 2.0, 0.48 * fsr)], btype="band", fs=fsr)
            s1 = hilbert(filtfilt(*b1, r["x"]))
            s3 = hilbert(filtfilt(*b3, r["x"]))
            r["_p1"], r["_p3"] = np.angle(s1), np.angle(s3)
            c = slice(NW // 8, -NW // 8)                      # drop filter edge transients
            r["plv"] = float(np.abs(np.mean(np.exp(1j * (3 * r["_p1"][c] - r["_p3"][c])))))
        # shuffled null: pair phi_1 of one window with phi_3 of another
        idx = RNG.permutation(len(rs))
        idx = np.where(idx == np.arange(len(rs)), (idx + 1) % len(rs), idx)
        c = slice(NW // 8, -NW // 8)
        for r, j in zip(rs, idx):
            r["plv_null"] = float(np.abs(np.mean(np.exp(
                1j * (3 * r["_p1"][c] - rs[j]["_p3"][c])))))
        u = [r["blk"] for r in rs]
        pv = _boot_med([r["plv"] for r in rs], u)
        nv = _boot_med([r["plv_null"] for r in rs], u)
        sd = float(np.std([r["plv_null"] for r in rs])) or np.nan
        z = (pv[0] - nv[0]) / sd if np.isfinite(sd) else np.nan
        print(f"{route:10s} {arm:8s} {len(rs):5d} | {pv[0]:6.4f} [{pv[1]:6.4f},{pv[2]:6.4f}] | "
              f"{nv[0]:6.4f} [{nv[1]:6.4f},{nv[2]:6.4f}] | {z:6.2f}")
        OUT["t2"][f"{route}|{arm}"] = dict(n=len(rs), plv=list(pv), null=list(nv), z=float(z))
        for r in rs:
            r.pop("_p1", None); r.pop("_p3", None)
    print("\n  🛑 READ: PLV indistinguishable from the shuffled null ⇒ the 3rd harmonic is NOT\n"
          "     phase-generated by the fundamental ⇒ no relay.")


# =====================================================================================================
#  T3 -- speed-locked vs fixed line
# =====================================================================================================
def t3(W):
    hdr("T3  SPEED-LOCKED vs FIXED LINE in 5-12 Hz -- the tyre/firmware split, and the best\n"
        "    available handle on micro- versus macro-ratcheting.")
    OUT["t3"] = {}
    for route, arm, recs in W:
        if arm != "engaged":
            continue
        rs = [r for r in recs if np.isfinite(r["f_free"])]
        if len(rs) < 20:
            continue
        for r in rs:
            r["p_fix"] = prom_at(r, MACRO, half=0.5)
            o2 = 2 * r["v"] / CIRC
            r["o2"] = o2
            r["p_o2"] = (prom_at(r, o2, half=0.5)
                         if (4.0 <= o2 <= 20.0 and abs(o2 - MACRO) >= 1.2) else np.nan)
        u = [r["blk"] for r in rs]
        pf = _boot_med([r["p_fix"] for r in rs], u)
        po = _boot_med([r["p_o2"] for r in rs], u)
        # does the FREE argmax track speed?
        v = np.array([r["v"] for r in rs]); ff = np.array([r["f_free"] for r in rs])
        A = np.vstack([v, np.ones_like(v)]).T
        slope = float(np.linalg.lstsq(A, ff, rcond=None)[0][0])
        near_fix = float(np.mean(np.abs(ff - MACRO) <= 0.6))
        near_o2 = float(np.mean([abs(r["f_free"] - r["o2"]) <= 0.6 for r in rs]))
        print(f"\n  {route}  n={len(rs)}")
        print(f"    prominence at the FIXED {MACRO} Hz line : {pf[0]:6.2f} [{pf[1]:5.2f},{pf[2]:5.2f}]"
              f"  (n={pf[3]})")
        print(f"    prominence at WHEEL ORDER 2            : {po[0]:6.2f} [{po[1]:5.2f},{po[2]:5.2f}]"
              f"  (n={po[3]}, order-2 away from {MACRO} Hz)")
        print(f"    free 5-12 Hz argmax: median {np.median(ff):5.2f} Hz, slope vs v "
              f"{slope:+.4f} Hz per m/s   (order-2 predicts +0.961, a fixed line 0.000)")
        print(f"    fraction of windows whose argmax is within 0.6 Hz of "
              f"{MACRO} Hz: {100*near_fix:5.1f}%   of order-2: {100*near_o2:5.1f}%")
        # speed-binned median of the free argmax -- the ridge test
        print(f"    {'v bin m/s':>12s} {'n':>4s} {'median argmax':>14s} {'order2':>8s}")
        for lo, hi in ((0, 2), (2, 4), (4, 6), (6, 8), (8, 11), (11, 16), (16, 40)):
            m = [r for r in rs if lo <= r["v"] < hi]
            if len(m) < 5:
                continue
            print(f"    {f'{lo}-{hi}':>12s} {len(m):4d} "
                  f"{np.median([r['f_free'] for r in m]):14.2f} "
                  f"{np.median([r['o2'] for r in m]):8.2f}")
        OUT["t3"][route] = dict(n=len(rs), p_fix=list(pf), p_o2=list(po), slope=slope,
                                near_fix=near_fix, near_o2=near_o2,
                                f_free_med=float(np.median(ff)))
    print("\n  🛑 READ: a slope near +0.961 and argmax tracking order 2 ⇒ the 6-9 Hz band on that\n"
          "     route is largely TYRE, not firmware.  A slope near 0 with a fixed ridge ⇒ firmware.")


# =====================================================================================================
#  T4 -- switching-surface timing
# =====================================================================================================
def t4(W):
    hdr("T4  SWITCHING-SURFACE TIMING.  Zero-crossing-triggered average of the 6-9 Hz envelope,\n"
        "    triggered on the 0.5-4 Hz residual's zero crossings.  Bands are DISJOINT.\n"
        "    NULL: the same count of pseudo-crossings placed uniformly at random.")
    OUT["t4"] = {}
    LAGS = np.arange(-30, 31)                    # +-0.3 s at ~101 Hz
    print(f"{'build':10s} {'arm':8s} {'n win':>6s} {'n cross':>8s} | "
          f"{'peak lag ms':>12s} {'ETA peak / baseline':>21s} | {'NULL peak/base':>16s}")
    for route, arm, recs in W:
        rs = [r for r in recs if len(r["env"]) == NW]
        if len(rs) < 10:
            continue
        acc, accn, ncr = [], [], 0
        for r in rs:
            e = r["env"] / (np.median(r["env"]) + 1e-9)
            z = r["x_lf"]
            cr = np.flatnonzero((z[:-1] < 0) & (z[1:] >= 0)) + 1
            cr = cr[(cr > 40) & (cr < NW - 40)]
            if len(cr) < 2:
                continue
            ncr += len(cr)
            acc.append(np.mean([e[c + LAGS] for c in cr], axis=0))
            pc = RNG.integers(40, NW - 40, len(cr))
            accn.append(np.mean([e[c + LAGS] for c in pc], axis=0))
        if not acc:
            continue
        A = np.mean(acc, axis=0); N = np.mean(accn, axis=0)
        base = np.mean(np.r_[A[:10], A[-10:]])
        pk = int(np.argmax(A))
        nbase = np.mean(np.r_[N[:10], N[-10:]])
        print(f"{route:10s} {arm:8s} {len(acc):6d} {ncr:8d} | "
              f"{1000*LAGS[pk]/101.0:12.1f} {A[pk]/base:21.4f} | "
              f"{np.max(N)/nbase:16.4f}")
        OUT["t4"][f"{route}|{arm}"] = dict(n=len(acc), ncross=ncr,
                                           peak_lag_ms=float(1000 * LAGS[pk] / 101.0),
                                           eta=float(A[pk] / base),
                                           null=float(np.max(N) / nbase),
                                           curve=[float(x) for x in A])
    print("\n  🛑 READ: ETA peak/baseline at the SAME level as the random-placement null ⇒ the\n"
        "     6-9 Hz envelope is NOT time-locked to the residual's switching surface.")


# =====================================================================================================
#  T5 -- conditioning on V85's friction rungs
# =====================================================================================================
def t5(W):
    hdr("T5  IS THE 6-9 Hz CONTENT CONDITIONAL ON `|gp-0x6ae2|`?  V85 only -- the rungs exist on\n"
        "    no other build.  ⚠ `gp-0x6ae2` is the term `0xC40BC` linearised, NOT `gp-0x6b70`.")
    recs = [r for rt, arm, rr in W if rt == "V85/r6e" and arm == "engaged" for r in rr]
    if not recs:
        print("  no V85 engaged windows"); return
    b_bp = butter(2, [F_LO, F_HI], btype="band", fs=101.0)
    for r in recs:
        r["e69"] = float(np.percentile(np.abs(hilbert(filtfilt(*b_bp, r["x"]))), 99))
    print(f"{'rung':6s} {'split':>26s} {'n lo':>5s} {'n hi':>5s} | {'e_6-9 LOW':>22s} | "
          f"{'e_6-9 HIGH':>22s} | {'HIGH/LOW':>8s}")
    OUT["t5"] = {}
    for rung, name in (("b4", "|gp-0x6ae2| >= 2"), ("b5", "|gp-0x6ae2| >= 8"),
                       ("b7", "|gp-0x6abc| >= 64"), ("b6", "|gp-0x6abc| >= 512")):
        duty = np.array([r[rung] for r in recs])
        thr = float(np.median(duty))
        lo_ = [r for r in recs if r[rung] <= thr]
        hi_ = [r for r in recs if r[rung] > thr]
        if len(lo_) < 8 or len(hi_) < 8:
            print(f"{rung:6s} {name:>26s}  -- degenerate split ({len(lo_)}/{len(hi_)}) --")
            continue
        a = _boot_med([r["e69"] for r in lo_], [r["blk"] for r in lo_])
        b = _boot_med([r["e69"] for r in hi_], [r["blk"] for r in hi_])
        print(f"{rung:6s} {name:>26s} {len(lo_):5d} {len(hi_):5d} | "
              f"{a[0]:8.1f} [{a[1]:6.1f},{a[2]:6.1f}] | {b[0]:8.1f} [{b[1]:6.1f},{b[2]:6.1f}] | "
              f"{b[0]/a[0]:8.3f}")
        OUT["t5"][rung] = dict(thr=thr, lo=list(a), hi=list(b), ratio=float(b[0] / a[0]))
    print("\n  ⚠ CONFOUNDED BY SPEED: every rung's duty falls with speed, and so does e_6-9.\n"
          "    The speed-matched version is the row below.")
    # speed-matched: within each 2 m/s bin, compare above/below the bin's own median duty
    for rung in ("b4", "b5"):
        rs_lo, rs_hi = [], []
        for lo, hi in ((0, 2), (2, 4), (4, 6), (6, 8), (8, 12), (12, 30)):
            m = [r for r in recs if lo <= r["v"] < hi]
            if len(m) < 10:
                continue
            thr = float(np.median([r[rung] for r in m]))
            rs_lo += [r for r in m if r[rung] <= thr]
            rs_hi += [r for r in m if r[rung] > thr]
        if len(rs_lo) < 8 or len(rs_hi) < 8:
            continue
        a = _boot_med([r["e69"] for r in rs_lo], [r["blk"] for r in rs_lo])
        b = _boot_med([r["e69"] for r in rs_hi], [r["blk"] for r in rs_hi])
        print(f"  speed-matched {rung}: LOW {a[0]:7.1f} [{a[1]:.1f},{a[2]:.1f}] (n={a[3]})  "
              f"HIGH {b[0]:7.1f} [{b[1]:.1f},{b[2]:.1f}] (n={b[3]})  ratio {b[0]/a[0]:.3f}")
        OUT["t5"][rung + "_speedmatched"] = dict(lo=list(a), hi=list(b), ratio=float(b[0] / a[0]))


def main():
    w0()
    W = []
    for route, cache, pfx, segs in ROUTES:
        for arm, en in (("engaged", True), ("manual", False)):
            rs = spectra(windows(route, cache, pfx, segs, engaged=en))
            print(f"  {route} {arm}: {len(rs)} windows of {NW} samples", flush=True)
            W.append((route, arm, rs))
    t1(W)
    t2(W)
    t3(W)
    t4(W)
    t5(W)
    (ROOT / "_scratch/cache/r6e" / "relay_fingerprint_r6e.json").write_text(json.dumps(OUT, indent=1))
    print(f"\nwrote {ROOT / '_scratch/cache/r6e' / 'relay_fingerprint_r6e.json'}")


if __name__ == "__main__":
    main()
